// ─────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by plugins/build.js — do not edit by hand.
// Source: plugins/minipaint/src/
// ─────────────────────────────────────────────────────────────────────
"use strict";
(() => {
  // minipaint/src/state.ts
  var TAB_ID = "minipaint", state = {
    outputDir: localStorage.getItem("minipaint-output-dir") || "",
    busy: !1
  };
  function setOutputDir(value) {
    state.outputDir = value, localStorage.setItem("minipaint-output-dir", value);
  }

  // minipaint/src/ipc.ts
  var PH = window.PluginHost;
  async function checkInstalled() {
    var _a2;
    let resp = await PH.callService("CheckPluginRuntimeInstalled", { plugin: "minipaint" });
    return !!((_a2 = resp == null ? void 0 : resp.CheckPluginRuntimeInstalledResult) != null && _a2.installed);
  }
  async function startInstallation() {
    var _a2;
    let resp = await PH.callService("InstallPluginRuntime", { plugin: "minipaint" });
    return !!((_a2 = resp == null ? void 0 : resp.InstallPluginRuntimeResult) != null && _a2.started);
  }
  async function getProgress() {
    var _a2;
    let resp = await PH.callService("GetPluginRuntimeInstallProgress", { plugin: "minipaint" });
    return (_a2 = resp == null ? void 0 : resp.GetPluginRuntimeInstallProgressResult) != null ? _a2 : { status: "idle", percent: 0, logs: [] };
  }
  async function saveEditedImage(p) {
    var _a2;
    let tauriCore = (_a2 = window.__TAURI__) == null ? void 0 : _a2.core;
    if (!tauriCore)
      throw new Error("Tauri core API not available; cannot save edited image.");
    return { ok: !0, path: await tauriCore.invoke(
      "save_edited_image",
      new Uint8Array(p.bytes),
      {
        headers: {
          "x-filename": encodeURIComponent(p.name),
          "x-format": p.format,
          "x-out-dir": encodeURIComponent(p.outputDir)
        }
      }
    ) };
  }

  // lib/log.ts
  var LOG_COLORS = {
    info: "#cccccc",
    success: "#10b981",
    error: "#f87171"
  };
  function createLogger(elementId) {
    return function(message, kind = "info") {
      let box = document.getElementById(elementId);
      if (!box) return;
      let line = document.createElement("div");
      line.style.cssText = `font-family:'Consolas',monospace;font-size:11px;line-height:1.4;color:${LOG_COLORS[kind]};white-space:pre-wrap;word-break:break-all;`, line.textContent = message, box.appendChild(line), box.scrollTop = box.scrollHeight;
    };
  }

  // lib/ipc-utils.ts
  var PH2 = window.PluginHost;

  // lib/navigation.ts
  function navigateToTab(tabId) {
    let item = document.querySelector(
      `.nav-item[data-view="extensions-${tabId}"]`
    );
    item && item.click();
  }
  function closeInfoModal() {
    var _a2;
    if ((_a2 = window.PluginHost) != null && _a2.closeImageViewer)
      window.PluginHost.closeImageViewer();
    else {
      let viewerModal = document.getElementById("image-viewer-modal");
      viewerModal != null && viewerModal.classList.contains("active") && viewerModal.classList.remove("active");
    }
    let modal = document.getElementById("image-info-modal");
    if (!(modal != null && modal.classList.contains("active"))) return;
    let closeBtn = modal.querySelector(".modal-close");
    closeBtn ? closeBtn.click() : modal.classList.remove("active");
  }

  // lib/poll.ts
  var PH3 = window.PluginHost;

  // minipaint/src/installer.ts
  function renderInstaller(onComplete) {
    let container = document.createElement("div");
    container.className = "group-box", container.style.cssText = "margin-top:8px;", container.innerHTML = `
    <div class="group-box-title"><i class="bi bi-palette"></i> miniPaint Editor Setup</div>
    <div style="font-size:11px;margin-bottom:12px;line-height:1.5;color:#555;">
      miniPaint (v4.14.3) is not installed locally. Click below to download and extract
      the editor runtime \u2014 it is served entirely offline from this machine.
    </div>
    <button type="button" class="win-button primary" id="minipaint-install-btn">
      <i class="bi bi-download"></i> Download &amp; Install Editor
    </button>
    <div class="group-box" style="margin-top:12px;">
      <div class="group-box-title"><i class="bi bi-terminal"></i> Install Console</div>
      <div id="minipaint-install-log" style="height:180px;overflow-y:auto;background-color:#1e1e1e;color:#cccccc;border:1px solid #7a7a7a;padding:8px;font-family:'Consolas',monospace;font-size:11px;white-space:pre-wrap;"></div>
    </div>
  `;
    let log = createLogger("minipaint-install-log"), btn = container.querySelector("#minipaint-install-btn");
    btn.addEventListener("click", async () => {
      btn.disabled = !0, log("Starting install task\u2026", "info");
      let started = !1;
      try {
        started = await startInstallation();
      } catch (e) {
        let msg = e instanceof Error ? e.message : String(e);
        log(`Failed to launch installer: ${msg}`, "error"), btn.disabled = !1;
        return;
      }
      started || log("An install is already running; polling existing task.", "info"), pollProgress();
    });
    function pollProgress() {
      let rendered = 0, timer = setInterval(async () => {
        let prog;
        try {
          prog = await getProgress();
        } catch (e) {
          return;
        }
        let box = document.getElementById("minipaint-install-log");
        if (box && prog.logs && prog.logs.length > rendered) {
          let docFrag = document.createDocumentFragment();
          for (let i = rendered; i < prog.logs.length; i++) {
            let line = document.createElement("div");
            line.style.cssText = "font-family:'Consolas',monospace;font-size:11px;line-height:1.4;color:#cccccc;white-space:pre-wrap;word-break:break-all;", line.textContent = prog.logs[i], docFrag.appendChild(line);
          }
          box.appendChild(docFrag), rendered = prog.logs.length, box.scrollTop = box.scrollHeight;
        }
        prog.status === "completed" ? (clearInterval(timer), log("Install completed.", "success"), onComplete()) : prog.status === "failed" && (clearInterval(timer), log(`Install failed: ${prog.error || "unknown error"}`, "error"), btn.disabled = !1);
      }, 500);
    }
    return container;
  }

  // minipaint/src/editor.ts
  var PH4 = window.PluginHost, currentFrame = null, editorWorkspaceRoot = "";
  async function onMessage(ev) {
    var _a2, _b2, _c, _d;
    if (ev.source !== (currentFrame == null ? void 0 : currentFrame.contentWindow)) return;
    let d = ev.data;
    if (!(!d || typeof d != "object")) {
      if (d.type === "minipaint:console-error") {
        console.error(
          `[minipaint iframe] ${d.message || "unknown error"}${d.detail ? `
` + d.detail : ""}`
        );
        return;
      }
      if (d.type === "minipaint:save") {
        let bytes = (_a2 = d.buffer) != null ? _a2 : d;
        if (!(bytes instanceof ArrayBuffer)) {
          (_b2 = currentFrame == null ? void 0 : currentFrame.contentWindow) == null || _b2.postMessage(
            { type: "minipaint:save-result", ok: !1, error: "no buffer in save message" },
            "*"
          );
          return;
        }
        let outFolder = state.outputDir || `${editorWorkspaceRoot}\\edited`, name = String(d.name || "edited");
        try {
          let res = await saveEditedImage({
            outputDir: outFolder,
            format: String(d.format || "png"),
            name,
            bytes
          });
          (_c = currentFrame == null ? void 0 : currentFrame.contentWindow) == null || _c.postMessage(
            { type: "minipaint:save-result", ok: res.ok, path: res.path, error: res.error },
            "*"
          );
        } catch (e) {
          (_d = currentFrame == null ? void 0 : currentFrame.contentWindow) == null || _d.postMessage(
            { type: "minipaint:save-result", ok: !1, error: String(e) },
            "*"
          );
        }
      }
    }
  }
  window.addEventListener("message", onMessage);
  function assetDirUrl(absPath) {
    let origin = PH4.convertFileSrc(""), encoded = absPath.split("\\").map((segment) => encodeURIComponent(segment)).join("/");
    return `${origin}${encoded}`;
  }
  function mountEditor(pluginDir, workspaceRoot, host, initialPath) {
    editorWorkspaceRoot = workspaceRoot;
    let iframe = document.createElement("iframe");
    iframe.style.cssText = "flex:1;width:100%;border:1px solid #ddd;background:#fff;", iframe.setAttribute("allow", "clipboard-write; web-share");
    function loadInitialAsset() {
      iframe.src = assetDirUrl(`${pluginDir}\\editor\\index.html`), initialPath && iframe.addEventListener(
        "load",
        () => {
          var _a2;
          (_a2 = iframe.contentWindow) == null || _a2.postMessage(
            { type: "minipaint:load-image", url: PH4.convertFileSrc(initialPath) },
            "*"
          );
        },
        { once: !0 }
      );
    }
    return host.appendChild(iframe), currentFrame = iframe, loadInitialAsset(), () => {
      iframe.remove(), currentFrame = null;
    };
  }
  function loadAssetIntoEditor(path) {
    var _a2;
    !currentFrame || !path || (_a2 = currentFrame.contentWindow) == null || _a2.postMessage(
      { type: "minipaint:load-image", url: PH4.convertFileSrc(path) },
      "*"
    );
  }
  async function browseOutputDir(onSelected) {
    var _a2, _b2;
    try {
      let selected = await ((_b2 = (_a2 = window.__TAURI__) == null ? void 0 : _a2.core) == null ? void 0 : _b2.invoke("select_path", { isDirectory: !0 }));
      selected && (setOutputDir(selected), onSelected(selected));
    } catch (e) {
      console.error("minipaint: folder picker failed", e);
    }
  }

  // minipaint/src/index.ts
  var PH5 = window.PluginHost, _a, _b;
  if (!PH5)
    console.error("minipaint: PluginHost not available; aborting.");
  else {
    if (!document.getElementById("minipaint-styles")) {
      let style = document.createElement("style");
      style.id = "minipaint-styles", style.textContent = `
      #view-extensions-minipaint.active {
        display: flex !important;
        flex-direction: column;
        flex: 1;
        min-height: 0;
        overflow: hidden !important;
      }
    `, document.head.appendChild(style);
    }
    let pluginDir = (_a = window.__curator_plugin_dir__) != null ? _a : "", workspaceRoot = (_b = window.__curator_workspace_root__) != null ? _b : "", editorHost = null, toggleBtn = null, editorMounted = !1, teardown = null, updateToggle = () => {
      toggleBtn && (toggleBtn.innerHTML = editorMounted ? '<i class="bi bi-stop-circle"></i> Unload Editor' : '<i class="bi bi-play-circle"></i> Load Editor');
    }, ensureEditor = (initialPath) => {
      if (editorMounted) {
        initialPath && loadAssetIntoEditor(initialPath);
        return;
      }
      editorHost && (teardown = mountEditor(pluginDir, workspaceRoot, editorHost, initialPath), editorMounted = !0, updateToggle());
    }, unloadEditor = () => {
      teardown == null || teardown(), teardown = null, editorMounted = !1, updateToggle();
    };
    PH5.registerMetadataRenderer("minipaint-send", (asset) => {
      var _a2;
      if (!(asset != null && asset.path)) return null;
      let box = document.createElement("div");
      return box.className = "group-box", box.style.cssText = "margin-top:8px;", box.innerHTML = '<div class="group-box-title"><i class="bi bi-palette"></i> Image Editor</div><div style="display:flex;align-items:center;gap:8px;padding:2px 0;">  <span style="font-size:11px;color:#555;flex:1;">Open this image in the miniPaint editor. The editor loads on demand and stays parked otherwise.</span>  <button type="button" class="win-button" id="minipaint-send-asset">    <i class="bi bi-brush"></i> Send to Editor  </button></div>', (_a2 = box.querySelector("#minipaint-send-asset")) == null || _a2.addEventListener("click", () => {
        closeInfoModal(), navigateToTab(TAB_ID), ensureEditor(asset.path);
      }), box;
    }), PH5.registerTab(TAB_ID, "Image Editor", "bi bi-palette", () => {
      let rootEl = document.createElement("div");
      rootEl.style.cssText = "width:100%;height:100%;display:flex;flex-direction:column;";
      let settingsBox = document.createElement("div");
      settingsBox.className = "group-box", settingsBox.style.cssText = "padding:8px;flex-shrink:0;";
      let title = document.createElement("div");
      title.className = "group-box-title", title.innerHTML = '<i class="bi bi-gear"></i> miniPaint Settings';
      let settingsRow = document.createElement("div");
      settingsRow.style.cssText = "display:flex;align-items:center;gap:8px;";
      let outputLabel = document.createElement("span");
      outputLabel.style.cssText = "font-size:11px;color:#555;", outputLabel.textContent = "Output Directory:";
      let outputInput = document.createElement("input");
      outputInput.type = "text", outputInput.className = "win-input", outputInput.value = state.outputDir || `${workspaceRoot}\\edited`, outputInput.style.cssText = "flex:1;font-size:11px;", outputInput.readOnly = !0;
      let browseBtn = document.createElement("button");
      browseBtn.type = "button", browseBtn.className = "win-button", browseBtn.style.cssText = "font-size:11px;", browseBtn.innerHTML = '<i class="bi bi-folder2-open"></i> Browse', browseBtn.addEventListener("click", () => {
        browseOutputDir((dir) => {
          outputInput.value = dir;
        });
      }), toggleBtn = document.createElement("button"), toggleBtn.type = "button", toggleBtn.className = "win-button", toggleBtn.style.cssText = "font-size:11px;", updateToggle(), toggleBtn.addEventListener("click", () => {
        editorMounted ? unloadEditor() : (ensureEditor(), installerEl && (installerEl.style.display = "none", installerEl = null));
      }), settingsRow.appendChild(toggleBtn), settingsRow.appendChild(outputLabel), settingsRow.appendChild(outputInput), settingsRow.appendChild(browseBtn), settingsBox.appendChild(title), settingsBox.appendChild(settingsRow), editorHost = document.createElement("div"), editorHost.style.cssText = "display:flex;flex-direction:column;width:100%;flex:1;min-height:0;";
      let launcherHost = document.createElement("div");
      launcherHost.style.cssText = "display:flex;flex-direction:column;width:100%;min-height:0;";
      let installerEl = null, onInstallComplete = () => {
        launcherHost.appendChild(settingsBox);
      };
      return (() => {
        launcherHost.innerHTML = "", installerEl = null, checkInstalled().then((installed) => {
          installed ? launcherHost.appendChild(settingsBox) : (installerEl = renderInstaller(onInstallComplete), launcherHost.appendChild(installerEl));
        });
      })(), rootEl.appendChild(launcherHost), rootEl.appendChild(editorHost), rootEl;
    }, !0);
  }
})();
