// ─────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by plugins/build.js — do not edit by hand.
// Source: plugins/aria2-downloader/src/
// ─────────────────────────────────────────────────────────────────────
"use strict";
(() => {
  // lib/log.ts
  var LOG_COLORS = {
    info: "#cccccc",
    success: "#10b981",
    error: "#f87171"
  }, CONSOLE_LINE_CSS = "font-family:'Consolas',monospace;font-size:11px;line-height:1.4;color:#cccccc;white-space:pre-wrap;word-break:break-all;";
  function appendLogLines(elementId, lines, fromIndex) {
    let box = document.getElementById(elementId);
    if (!box || fromIndex >= lines.length) return lines.length;
    let docFrag = document.createDocumentFragment();
    for (let i = fromIndex; i < lines.length; i++) {
      let line = document.createElement("div");
      line.style.cssText = CONSOLE_LINE_CSS, line.textContent = lines[i], docFrag.appendChild(line);
    }
    return box.appendChild(docFrag), box.scrollTop = box.scrollHeight, lines.length;
  }
  function createLogger(elementId) {
    return function(message, kind = "info") {
      let box = document.getElementById(elementId);
      if (!box) return;
      let line = document.createElement("div");
      line.style.cssText = kind === "info" ? CONSOLE_LINE_CSS : `font-family:'Consolas',monospace;font-size:11px;line-height:1.4;color:${LOG_COLORS[kind]};white-space:pre-wrap;word-break:break-all;`, line.textContent = message, box.appendChild(line), box.scrollTop = box.scrollHeight;
    };
  }

  // lib/format.ts
  function formatBytes(bytes, fallback = "", decimals = 2) {
    var _a;
    if (bytes == null || isNaN(bytes) || bytes < 0) return fallback;
    if (bytes === 0) return "0 B";
    let units = ["B", "KB", "MB", "GB", "TB"], i = Math.floor(Math.log(bytes) / Math.log(1024));
    return `${(bytes / Math.pow(1024, i)).toFixed(decimals)} ${(_a = units[i]) != null ? _a : "B"}`;
  }

  // lib/ipc-utils.ts
  var PH = window.PluginHost;
  async function pickDirectory() {
    return pickPath(!0);
  }
  async function pickPath(isDirectory) {
    var _a;
    let api = window.__TAURI__;
    if (!((_a = api == null ? void 0 : api.core) != null && _a.invoke)) return null;
    try {
      let selected = await api.core.invoke("select_path", { isDirectory });
      return typeof selected == "string" && selected.length > 0 ? selected : null;
    } catch (e) {
      return null;
    }
  }
  function getPluginDirs() {
    var _a, _b;
    return {
      pluginDir: (_a = window.__curator_plugin_dir__) != null ? _a : "",
      workspaceRoot: (_b = window.__curator_workspace_root__) != null ? _b : ""
    };
  }

  // lib/db.ts
  var PH2 = window.PluginHost;
  function createPluginDb(dbName) {
    return {
      async execute(sql, params = []) {
        var _a, _b;
        let resp = await PH2.callService("PluginDbExecute", { db: dbName, sql, params });
        if (resp != null && resp.Error) throw new Error(String(resp.Error.message));
        return Number((_b = (_a = resp == null ? void 0 : resp.PluginDbExecuteResult) == null ? void 0 : _a.rows_affected) != null ? _b : 0);
      },
      async query(sql, params = []) {
        var _a, _b;
        let resp = await PH2.callService("PluginDbQuery", { db: dbName, sql, params });
        if (resp != null && resp.Error) throw new Error(String(resp.Error.message));
        return (_b = (_a = resp == null ? void 0 : resp.PluginDbQueryResult) == null ? void 0 : _a.rows) != null ? _b : [];
      }
    };
  }

  // lib/fs.ts
  var PH3 = window.PluginHost;

  // lib/storage.ts
  function loadPersisted(key, fallback) {
    try {
      return localStorage.getItem(key) || fallback;
    } catch (e) {
      return fallback;
    }
  }
  function savePersisted(key, value) {
    try {
      localStorage.setItem(key, value);
    } catch (e) {
    }
  }

  // lib/poll.ts
  var PH4 = window.PluginHost;
  function pollServiceProgress({
    fetch,
    isRunning,
    onTick,
    onComplete,
    intervalMs = 500
  }) {
    let tick = async () => {
      let value;
      try {
        value = await fetch();
      } catch (e) {
        onComplete(!1);
        return;
      }
      if (value === void 0) {
        setTimeout(tick, intervalMs);
        return;
      }
      if (onTick(value), !isRunning(value)) {
        onComplete(!0, value);
        return;
      }
      setTimeout(tick, intervalMs);
    };
    tick();
  }

  // aria2-downloader/src/state.ts
  var TAB_ID = "aria2-downloader", ARIA2_TOOL = "aria2", DEFAULT_CONNECTIONS = 8, DEFAULT_MAX_TRIES = 5, { workspaceRoot } = getPluginDirs(), state = {
    queue: /* @__PURE__ */ new Map(),
    history: [],
    settings: {
      outputDir: workspaceRoot ? `${workspaceRoot.replace(/[\\/]+$/, "")}\\Downloads` : "",
      connections: DEFAULT_CONNECTIONS,
      speedLimitKb: 0,
      maxTries: DEFAULT_MAX_TRIES,
      autoRename: !1,
      autoStart: !0
    },
    toolAvailable: !1,
    toolVersion: null,
    toolInstalling: !1
  };
  function filenameFromUrl(url, fallbackIndex) {
    try {
      let seg = new URL(url).pathname.split("/").filter(Boolean).pop();
      if (seg) {
        let cleaned = decodeURIComponent(seg).replace(/[<>:"/\\|?*\u0000-\u001f]/g, "_").trim();
        if (cleaned) return cleaned;
      }
    } catch (e) {
    }
    return `download_${Date.now()}_${fallbackIndex}.bin`;
  }

  // aria2-downloader/src/ui-core.ts
  var PH5 = window.PluginHost;
  function el(id) {
    return document.getElementById(id);
  }
  var log = createLogger("ad-log");

  // aria2-downloader/src/ui-utils.ts
  function joinPath(dir, name) {
    let sep = dir.endsWith("\\") || dir.endsWith("/") ? "" : "\\";
    return `${dir}${sep}${name}`;
  }
  function isAbsolutePath(p) {
    return p ? /^[a-zA-Z]:[\\/]/.test(p) || p.startsWith("\\\\") || p.startsWith("/") : !1;
  }
  function formatEta(secs) {
    if (secs == null || secs < 0) return "\u2014";
    let h = Math.floor(secs / 3600), m = Math.floor(secs % 3600 / 60), s = Math.floor(secs % 60);
    return h > 0 ? `${h}h ${m}m` : m > 0 ? `${m}m ${s}s` : `${s}s`;
  }
  function formatRate(bps) {
    return bps ? `${formatBytes(bps, "0 B", 1)}/s` : "0 B/s";
  }
  function hostFromUrl(url) {
    try {
      return new URL(url).hostname.replace(/^www\./, "");
    } catch (e) {
      return url.split(/[\\/]/)[0] || url;
    }
  }
  function formatDateTime(epochSecs) {
    let d = new Date(epochSecs * 1e3), pad = (n) => String(n).padStart(2, "0");
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }
  function formatDuration(startedAt, completedAt) {
    let s = Math.max(0, Math.round((completedAt - startedAt) / 1e3)), h = Math.floor(s / 3600), m = Math.floor(s % 3600 / 60), sec = s % 60;
    return h > 0 ? `${h}h ${m}m ${sec}s` : m > 0 ? `${m}m ${sec}s` : `${sec}s`;
  }
  function clampNum(v, min, max, fallback) {
    return Number.isFinite(v) ? Math.max(min, Math.min(max, v)) : fallback;
  }

  // aria2-downloader/src/columns.ts
  var COL_WIDTH_KEY = "aria2-downloader-col-", columnResizeState = null;
  function applyColumnWidths() {
    document.querySelectorAll(".ad-table thead th").forEach((th) => {
      var _a;
      let colKey = ((_a = th.className.match(/\bcol-\w+/)) != null ? _a : [""])[0];
      if (!colKey) return;
      let width = localStorage.getItem(COL_WIDTH_KEY + colKey);
      width && (th.style.width = `${width}px`);
    });
  }
  function columnResizeMouseDown(e) {
    var _a, _b;
    let target = e.target, th = (_a = target.closest) == null ? void 0 : _a.call(target, "th");
    if (!th || !th.closest(".ad-table")) return;
    let rect = th.getBoundingClientRect();
    if (e.clientX < rect.right - 5 || e.clientX > rect.right + 5) return;
    e.preventDefault();
    let colKey = ((_b = th.className.match(/\bcol-\w+/)) != null ? _b : [""])[0];
    colKey && (columnResizeState = {
      th,
      colKey,
      startX: e.clientX,
      startWidth: rect.width,
      liveWidth: rect.width
    }, document.body.style.cursor = "col-resize", document.body.style.userSelect = "none");
  }
  function columnResizeMouseMove(e) {
    if (!columnResizeState) return;
    let width = Math.max(40, columnResizeState.startWidth + (e.clientX - columnResizeState.startX));
    columnResizeState.liveWidth = width, columnResizeState.th.style.width = `${width}px`;
  }
  function columnResizeMouseUp() {
    columnResizeState && (localStorage.setItem(COL_WIDTH_KEY + columnResizeState.colKey, String(columnResizeState.liveWidth)), columnResizeState = null, document.body.style.cursor = "", document.body.style.userSelect = "");
  }
  var columnResizeWired = !1;
  function wireColumnResize() {
    columnResizeWired || (columnResizeWired = !0, document.addEventListener("mousedown", columnResizeMouseDown), document.addEventListener("mousemove", columnResizeMouseMove), document.addEventListener("mouseup", columnResizeMouseUp));
  }

  // aria2-downloader/src/styles.ts
  function injectStyles() {
    if (document.getElementById("ad-styles")) return;
    let style = document.createElement("style");
    style.id = "ad-styles", style.textContent = `
    #view-extensions-${TAB_ID}.active {
      display: flex !important;
      flex-direction: column;
      height: calc(100vh - 140px);
      max-height: calc(100vh - 140px);
      overflow: hidden !important;
    }
    .ad-workspace {
      display: flex;
      flex-direction: column;
      gap: 8px;
      height: 100%;
      max-height: 100%;
      overflow: hidden;
      padding: 8px;
      box-sizing: border-box;
      font-family: var(--sys-font-family, "Segoe UI", sans-serif);
      color: var(--sys-window-text, #000);
      background: var(--sys-window-bg, #f0f0f0);
    }
    .ad-toolbar { flex-shrink: 0; }
    .ad-banner {
      display: none;
      flex-shrink: 0;
      align-items: center;
      gap: 8px;
      padding: 8px 10px;
      margin-bottom: 4px;
      font-size: 11px;
      border: 1px solid var(--sys-border-dark, #b0b0b0);
      border-radius: 3px;
      background-color: var(--sys-status-bg, #f3f3f3);
      color: var(--sys-window-text, #000);
    }
    .ad-banner > i { color: #b45309; flex-shrink: 0; }
    .ad-banner-inner { flex: 1; min-width: 0; }
    .ad-banner-status {
      margin-top: 3px;
      font-size: 10px;
      color: var(--sys-text-subtle, #555);
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .ad-banner-progress {
      margin-top: 4px;
      height: 8px;
      background: #dcdcdc;
      border: 1px solid #c0c0c0;
      border-radius: 2px;
      overflow: hidden;
    }
    .ad-banner-fill { height: 100%; background: var(--sys-highlight-bg, #0078d7); width: 0%; }
    .ad-chips {
      display: flex;
      flex-wrap: wrap;
      gap: 4px;
      margin-top: 6px;
      max-height: 54px;
      overflow-y: auto;
    }
    .ad-chip {
      font-size: 10px;
      padding: 2px 8px;
      border: 1px solid var(--sys-border-light, #c0c0c0);
      background: var(--sys-window-bg, #fff);
      color: var(--sys-window-text, #333);
      border-radius: 2px;
      white-space: nowrap;
    }
    .ad-chip.ok { border-color: #10b981; color: #047857; }
    .ad-chip.warn { border-color: #f59e0b; color: #b45309; }
    .ad-chip.bad { border-color: #ef4444; color: #b91c1c; }
    .ad-middle {
      flex: 1;
      min-height: 0;
      display: flex;
      flex-direction: row;
      gap: 8px;
    }
    .ad-column {
      flex: 1;
      min-width: 0;
      display: flex;
      flex-direction: column;
      gap: 8px;
      min-height: 0;
    }
    .ad-queue-box { flex: 3; }
    .ad-history-box { flex: 2; }
    .ad-scroll {
      flex: 1;
      min-height: 0;
      overflow: auto;
      border: 1px solid var(--sys-border-light, #d0d0d0);
      background: var(--sys-window-bg, #fff);
    }
    .ad-row {
      display: flex;
      align-items: center;
      gap: 6px;
      padding: 4px 6px;
      font-size: 11px;
      border-bottom: 1px solid #ececec;
    }
    .ad-row:hover { background: #f4f6f8; }
    .ad-row-mono {
      flex: 1;
      min-width: 0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      font-family: 'Consolas', monospace;
      color: #1a1a2e;
    }
    .ad-error {
      width: 100%;
      color: #b91c1c;
      font-size: 10px;
      font-family: 'Consolas', monospace;
      word-break: break-all;
      white-space: pre-wrap;
    }
    .ad-badge {
      font-size: 10px;
      padding: 1px 7px;
      border-radius: 2px;
      border: 1px solid #c0c0c0;
      background: #f0f0f0;
      color: #444;
      flex-shrink: 0;
    }
    .ad-badge.running { border-color: #3b82f6; background: #dbeafe; color: #1d4ed8; }
    .ad-badge.completed { border-color: #10b981; background: #d1fae5; color: #047857; }
    .ad-badge.cancelled { border-color: #f59e0b; background: #fef3c7; color: #b45309; }
    .ad-badge.failed { border-color: #ef4444; background: #fee2e2; color: #b91c1c; }
    .ad-badge.queued { border-color: #9ca3af; background: #f3f4f6; color: #4b5563; }
    .ad-filter-btn {
      font-size: 10px;
      padding: 1px 8px;
    }
    .ad-filter-btn.active {
      border-color: #1d4ed8;
      background: #dbeafe;
      color: #1d4ed8;
    }
    .ad-table {
      width: 100%;
      border-collapse: collapse;
      table-layout: fixed;
    }
    .ad-table thead th {
      text-align: left;
      font-size: 10px;
      font-weight: 600;
      color: #555;
      padding: 4px 6px;
      border-bottom: 1px solid #d0d0d0;
      background: #f4f6f8;
      position: relative;
      user-select: none;
    }
    .ad-table thead th::after {
      content: "";
      position: absolute;
      top: 3px;
      right: 0;
      bottom: 3px;
      width: 2px;
      background: #c8ccd0;
      cursor: col-resize;
    }
    .ad-table thead th:hover::after { background: #0078d7; }
    .ad-table td {
      padding: 4px 6px;
      font-size: 11px;
      border-bottom: 1px solid #ececec;
      vertical-align: middle;
    }
    .ad-table tbody tr:hover { background: #f4f6f8; }
    .ad-table .col-status { width: 74px; }
    .ad-table .col-hoster { width: 88px; }
    .ad-table .col-progress { width: 150px; }
    .ad-table .col-size { width: 96px; }
    .ad-table .col-speed { width: 84px; }
    .ad-table .col-eta { width: 62px; }
    .ad-table .col-hdate { width: 122px; }
    .ad-table .col-actions { width: 150px; text-align: right; }
    .ad-progress-wrap {
      display: flex;
      align-items: center;
      gap: 6px;
      width: 100%;
    }
    .ad-progress {
      flex: 1;
      height: 8px;
      background: #e5e7eb;
      border: 1px solid #c0c0c0;
      border-radius: 2px;
      overflow: hidden;
    }
    .ad-progress-fill { height: 100%; background: #0078d7; width: 0%; }
    .ad-meta {
      color: #555;
      font-size: 10px;
      flex-shrink: 0;
      min-width: 0;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .ad-log-dock {
      flex-shrink: 0;
      display: flex;
      flex-direction: column;
      min-height: 0;
    }
    .ad-log-box {
      height: 110px;
      max-height: 140px;
      overflow-y: auto;
      background-color: #1e1e1e;
      color: #cccccc;
      border: 1px solid var(--sys-border-dark, #7a7a7a);
      padding: 6px 8px;
      font-family: 'Consolas', monospace;
      font-size: 11px;
      line-height: 1.4;
      white-space: pre-wrap;
      word-break: break-all;
      box-sizing: border-box;
    }
    /* The app's global universal font rule beats inheritance on child divs,
       so pin every dock line to Consolas explicitly. */
    .ad-log-box div {
      font-family: 'Consolas', monospace;
      font-size: 11px;
      line-height: 1.4;
      color: #cccccc;
      white-space: pre-wrap;
      word-break: break-all;
    }
    .ad-empty { padding: 12px; color: #9ca3af; font-size: 11px; text-align: center; }
    .ad-summary-row {
      display: flex;
      align-items: center;
      gap: 8px;
      margin-top: 6px;
    }
    .ad-summary-row input[type="number"] { width: 84px; font-size: 11px; }
    .ad-summary-row label { font-size: 10px; color: #555; flex-shrink: 0; }
    .ad-toggle {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      font-size: 10px;
      color: #444;
      cursor: pointer;
      user-select: none;
      white-space: nowrap;
    }
    .ad-toggle input[type="checkbox"] { margin: 0; accent-color: var(--sys-highlight-bg, #0078d7); }
    .ad-toolbar-row { display: flex; align-items: center; gap: 8px; margin-top: 6px; }
    .ad-url-input {
      flex: 1;
      min-height: 46px;
      resize: vertical;
      font-family: 'Consolas', monospace;
      font-size: 11px;
    }
  `, document.head.appendChild(style);
  }

  // aria2-downloader/src/sites.ts
  function checkUrlCompatibility(url) {
    let trimmed = url.trim();
    if (!trimmed)
      return {
        url: "",
        status: "unknown",
        label: "Invalid URL",
        badgeText: "Invalid",
        badgeColor: "#9ca3af"
      };
    if (trimmed.startsWith("ftp://") || trimmed.startsWith("ftps://"))
      return {
        url: trimmed,
        status: "verified_direct",
        label: "FTP / FTPS",
        badgeText: "Direct FTP Download",
        badgeColor: "#10b981"
      };
    let hostname = "";
    try {
      hostname = new URL(trimmed).hostname.toLowerCase();
    } catch (e) {
      let match = trimmed.match(/^https?:\/\/([^/?#]+)/i);
      hostname = match ? match[1].toLowerCase() : trimmed.toLowerCase();
    }
    return hostname = hostname.replace(/^www\./, ""), /\.(zip|rar|7z|tar|gz|xz|iso|img|mp4|mkv|avi|mov|mp3|flac|wav|png|jpg|jpeg|webp|pdf|epub|bin|exe|msi|dmg|deb|rpm)(\?.*)?$/i.test(trimmed) ? {
      url: trimmed,
      status: "generic_direct",
      label: `Direct File (${hostname})`,
      badgeText: "Direct HTTP Download",
      badgeColor: "#3b82f6"
    } : trimmed.startsWith("http://") || trimmed.startsWith("https://") ? {
      url: trimmed,
      status: "unknown",
      label: hostname || "Generic Link",
      badgeText: "Direct HTTP Download",
      badgeColor: "#f59e0b"
    } : {
      url: trimmed,
      status: "unknown",
      label: "Unsupported / Invalid",
      badgeText: "Unknown URL format",
      badgeColor: "#ef4444"
    };
  }

  // aria2-downloader/src/chips.ts
  function updateChips() {
    let input = el("ad-url-input"), chips = el("ad-chips");
    if (!input || !chips) return;
    let urls = splitUrls(input.value), visible = urls.slice(0, 12);
    if (chips.innerHTML = "", visible.length === 0) return;
    let queuedUrls = /* @__PURE__ */ new Set();
    for (let item of state.queue.values()) queuedUrls.add(item.url);
    let historyUrls = new Set(state.history.map((h) => h.url));
    for (let u of visible) {
      let r = checkUrlCompatibility(u), inQueue = queuedUrls.has(u), inHistory = !state.settings.autoRename && historyUrls.has(u), statusText = r.badgeText, chipClass = r.status === "verified_direct" ? "ok" : r.status === "generic_direct" ? "warn" : "bad";
      inQueue ? (statusText += " (In Queue)", chipClass = "warn") : inHistory && (statusText += " (Downloaded)", chipClass = "warn");
      let chip = document.createElement("span");
      chip.className = `ad-chip ${chipClass}`, chip.title = `${u}
${r.label} \u2014 ${statusText}`, chip.textContent = statusText, chips.appendChild(chip);
    }
    if (urls.length > visible.length) {
      let more = document.createElement("span");
      more.className = "ad-chip", more.textContent = `+${urls.length - visible.length} more`, chips.appendChild(more);
    }
  }
  function splitUrls(raw) {
    return Array.isArray(raw) ? raw.flatMap((s) => typeof s == "string" ? splitUrls(s) : []).filter(Boolean) : typeof raw != "string" ? [] : raw.split(/[\s,]+/).map((s) => s.trim()).filter(Boolean);
  }

  // aria2-downloader/src/ipc.ts
  var PH6 = window.PluginHost;
  async function checkTool(tool) {
    var _a, _b, _c;
    let resp = await PH6.callService("CheckTool", { tool }), r = resp == null ? void 0 : resp.CheckToolResult;
    return {
      installed: !!(r != null && r.installed),
      path: (_a = r == null ? void 0 : r.path) != null ? _a : null,
      version: (_b = r == null ? void 0 : r.version) != null ? _b : null,
      portablePath: (_c = r == null ? void 0 : r.portable_path) != null ? _c : null
    };
  }
  async function installTool(tool) {
    var _a;
    let resp = await PH6.callService("InstallTool", { tool }), r = resp == null ? void 0 : resp.InstallToolResult;
    return { started: !!(r != null && r.started), error: (_a = r == null ? void 0 : r.error) != null ? _a : null };
  }
  async function getToolInstallProgress(tool) {
    var _a, _b, _c, _d;
    let resp = await PH6.callService("GetToolInstallProgress", { tool }), r = resp == null ? void 0 : resp.GetToolInstallProgressResult;
    return {
      status: (_a = r == null ? void 0 : r.status) != null ? _a : "idle",
      percent: (_b = r == null ? void 0 : r.percent) != null ? _b : 0,
      logs: (_c = r == null ? void 0 : r.logs) != null ? _c : [],
      error: (_d = r == null ? void 0 : r.error) != null ? _d : null
    };
  }
  async function downloadStart(params) {
    let resp = await PH6.callService("DownloadStart", params);
    if (resp != null && resp.Error) throw new Error(String(resp.Error.message));
    let r = resp == null ? void 0 : resp.DownloadStartResult;
    if (!(r != null && r.job_id)) throw new Error("DownloadStart returned no job_id");
    return r.job_id;
  }
  async function downloadProgress(jobId) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l;
    let resp = await PH6.callService("DownloadProgress", { job_id: jobId });
    if (resp != null && resp.Error) throw new Error(String(resp.Error.message));
    let r = resp == null ? void 0 : resp.DownloadProgressResult;
    if (r)
      return {
        running: !!r.running,
        status: (_a = r.status) != null ? _a : "unknown",
        percent: (_b = r.percent) != null ? _b : 0,
        downloadedBytes: (_c = r.downloaded_bytes) != null ? _c : 0,
        totalBytes: (_d = r.total_bytes) != null ? _d : null,
        speedBps: (_e = r.speed_bps) != null ? _e : 0,
        etaSecs: (_f = r.eta_secs) != null ? _f : null,
        connections: (_g = r.connections) != null ? _g : 0,
        outputPath: (_h = r.output_path) != null ? _h : null,
        error: (_i = r.error) != null ? _i : null,
        logs: (_j = r.logs) != null ? _j : [],
        command: (_k = r.command) != null ? _k : null,
        engine: (_l = r.engine) != null ? _l : null
      };
  }
  async function downloadCancel(jobId) {
    let resp = await PH6.callService("DownloadCancel", { job_id: jobId });
    if (resp != null && resp.Error) throw new Error(String(resp.Error.message));
  }
  async function resolveOutputPath(jobId, outputPath, autoRename) {
    let resp = await PH6.callService("ResolveOutputPath", {
      job_id: jobId,
      output_path: outputPath,
      auto_rename: autoRename
    });
    if (resp != null && resp.Error) throw new Error(String(resp.Error.message));
    let r = resp == null ? void 0 : resp.ResolveOutputPathResult;
    if (!(r != null && r.output_path)) throw new Error("ResolveOutputPath returned no output_path");
    return r.output_path;
  }
  async function dbQuery(sql, params = [], db = "download_history.db") {
    return { rows: await createPluginDb(db).query(sql, params) };
  }
  async function dbExecute(sql, params = [], db = "download_history.db") {
    return createPluginDb(db).execute(sql, params);
  }
  async function revealInFolder(path) {
    var _a;
    let api = (_a = window.__TAURI__) == null ? void 0 : _a.core;
    if (!(api != null && api.invoke)) return !1;
    try {
      return await api.invoke("reveal_in_folder", { path }), !0;
    } catch (e) {
      return !1;
    }
  }

  // aria2-downloader/src/tool-status.ts
  function defaultBannerText() {
    return state.toolInstalling ? "Installing aria2 engine..." : "aria2 engine not found. Download & install it to enable multi-connection downloads.";
  }
  function setToolBanner(available, version, message, bannerEl) {
    let banner = bannerEl != null ? bannerEl : el("ad-banner"), text = banner == null ? void 0 : banner.querySelector("#ad-banner-text");
    if (!(!banner || !text)) {
      if (available) {
        banner.style.display = "none";
        return;
      }
      banner.style.display = "flex", text.textContent = message + (version ? ` (${version})` : "");
    }
  }
  async function refreshToolStatus(bannerEl) {
    try {
      let status = await checkTool(ARIA2_TOOL);
      state.toolAvailable = status.installed, state.toolVersion = status.version;
    } catch (err) {
      state.toolAvailable = !1, state.toolVersion = null, log(`Tool check failed: ${err instanceof Error ? err.message : String(err)}`, "error");
    }
    setToolBanner(state.toolAvailable, state.toolVersion, defaultBannerText(), bannerEl);
  }
  function runEngineInstall({ onStatus, onDone }) {
    let rendered = 0, finish = (ok, error) => {
      state.toolInstalling = !1, onDone && onDone(ok, error);
    }, poll = async () => {
      var _a, _b;
      let p;
      try {
        p = await getToolInstallProgress(ARIA2_TOOL);
      } catch (err) {
        p = { status: "error", percent: 0, logs: [String(err)], error: String(err) };
      }
      if (onStatus && onStatus(p.status, p.percent), rendered = appendLogLines("ad-log", p.logs, rendered), p.status === "completed" || p.status === "done") {
        log("Install complete.", "success"), await refreshToolStatus(), finish(!0, null);
        return;
      }
      if (p.status === "failed" || p.status === "error") {
        log(`Install failed: ${(_a = p.error) != null ? _a : p.status}`, "error"), finish(!1, (_b = p.error) != null ? _b : p.status);
        return;
      }
      setTimeout(() => void poll(), 1e3);
    };
    (async () => {
      try {
        let { started, error } = await installTool(ARIA2_TOOL);
        if (!started) {
          error ? (log(`Install could not start: ${error}`, "error"), finish(!1, error)) : (log("aria2 engine is already installed.", "success"), await refreshToolStatus(), finish(!0, null));
          return;
        }
      } catch (err) {
        log(`Install start failed: ${err instanceof Error ? err.message : String(err)}`, "error"), finish(!1, err instanceof Error ? err.message : String(err));
        return;
      }
      await poll();
    })();
  }
  async function installAria2() {
    if (state.toolInstalling) return;
    state.toolInstalling = !0;
    let installBtn = el("ad-install-btn");
    installBtn && (installBtn.disabled = !0);
    let statusEl = el("ad-banner-status"), progressEl = el("ad-banner-progress"), fill = el("ad-banner-fill");
    statusEl && (statusEl.style.display = "block", statusEl.textContent = "Starting install..."), progressEl && (progressEl.style.display = "block"), fill && (fill.style.width = "0%"), log("Installing aria2 engine...", "info"), runEngineInstall({
      onStatus: (status, percent) => {
        statusEl && (statusEl.textContent = `${status} ${percent}%`), fill && (fill.style.width = `${Math.max(0, Math.min(100, percent))}%`);
      },
      onDone: (ok, error) => {
        installBtn && (installBtn.disabled = !1), ok ? (statusEl && (statusEl.textContent = "Installed."), fill && (fill.style.width = "100%"), log("aria2 installed successfully.", "success")) : (statusEl && (statusEl.textContent = error != null ? error : "Install failed."), log(`aria2 install failed: ${error}`, "error"));
      }
    });
  }

  // aria2-downloader/src/history.ts
  var TRACKING_PARAMS = /* @__PURE__ */ new Set([
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_term",
    "utm_content",
    "fbclid",
    "gclid",
    "ref",
    "referrer",
    "spm"
  ]);
  function normalizeUrl(rawUrl) {
    let out;
    try {
      let u = new URL(rawUrl.trim());
      u.hash = "";
      for (let p of [...u.searchParams.keys()])
        TRACKING_PARAMS.has(p.toLowerCase()) && u.searchParams.delete(p);
      out = u.toString();
    } catch (e) {
      out = rawUrl.trim();
    }
    return out.toLowerCase();
  }
  async function ensureHistorySchema() {
    await dbExecute(`CREATE TABLE IF NOT EXISTS download_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    normalized_url TEXT NOT NULL,
    filename TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    error_message TEXT,
    completed_at INTEGER NOT NULL,
    package_name TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`), await dbExecute(
      "CREATE INDEX IF NOT EXISTS idx_download_history_url ON download_history(normalized_url)"
    ), await dbExecute(
      "CREATE INDEX IF NOT EXISTS idx_download_history_completed ON download_history(completed_at DESC)"
    ), await dbExecute(
      "CREATE UNIQUE INDEX IF NOT EXISTS idx_download_history_url_path ON download_history(normalized_url, file_path)"
    );
  }
  async function recordDownload(rec) {
    await dbExecute(
      `INSERT OR IGNORE INTO download_history
      (url, normalized_url, filename, file_path, file_size, status, error_message, completed_at, package_name)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        rec.url,
        rec.normalized_url,
        rec.filename,
        rec.file_path,
        rec.file_size,
        rec.status,
        rec.error_message,
        rec.completed_at || Math.floor(Date.now() / 1e3),
        rec.package_name
      ]
    );
  }
  async function queryHistory(limit = 200, offset = 0) {
    var _a;
    return (_a = (await dbQuery(
      "SELECT * FROM download_history ORDER BY completed_at DESC LIMIT ? OFFSET ?",
      [limit, offset]
    )).rows) != null ? _a : [];
  }
  async function searchHistory(term, limit = 200) {
    var _a;
    return (_a = (await dbQuery(
      `SELECT * FROM download_history
     WHERE filename LIKE ? OR status LIKE ? OR url LIKE ?
     ORDER BY completed_at DESC LIMIT ?`,
      [`%${term}%`, `%${term}%`, `%${term}%`, limit]
    )).rows) != null ? _a : [];
  }
  async function findDuplicateUrls(urls) {
    let normalized = urls.map(normalizeUrl);
    if (normalized.length === 0) return [];
    let placeholders = normalized.map(() => "?").join(","), res = await dbQuery(
      `SELECT normalized_url FROM download_history WHERE normalized_url IN (${placeholders})`,
      normalized
    ), seen = new Set(res.rows.map((r) => String(r.normalized_url)));
    return normalized.filter((n) => seen.has(n));
  }
  async function removeHistoryEntry(id) {
    await dbExecute("DELETE FROM download_history WHERE id = ?", [id]);
  }

  // aria2-downloader/src/log-dock.ts
  function appendLogDelta(item) {
    let dock = el("ad-log");
    if (!dock || item.logIndex >= item.logs.length) return;
    let frag = document.createDocumentFragment();
    for (let i = item.logIndex; i < item.logs.length; i++) {
      let line = document.createElement("div");
      line.textContent = item.logs[i], frag.appendChild(line);
    }
    dock.appendChild(frag), dock.scrollTop = dock.scrollHeight, item.logIndex = item.logs.length;
  }
  function clearLogDock() {
    let dock = el("ad-log");
    dock && (dock.innerHTML = "");
  }

  // aria2-downloader/src/queue.ts
  var lastQueueRender = 0, queueStatusFilter = "";
  function setQueueStatusFilter(status) {
    queueStatusFilter = status;
  }
  function renderQueueThrottled() {
    let now = performance.now();
    now - lastQueueRender < 350 || (lastQueueRender = now, renderQueue());
  }
  async function addUrls(raw) {
    let urls = splitUrls(raw);
    if (urls.length === 0) return { added: 0, skippedQueue: 0, skippedHistory: 0, total: 0 };
    if (!state.toolAvailable)
      return log("aria2 engine not installed - downloads are disabled until it is available.", "error"), setToolBanner(!1, state.toolVersion, defaultBannerText()), { added: 0, skippedQueue: 0, skippedHistory: 0, total: urls.length };
    let fresh = urls, skippedQueueCount = 0;
    if (!state.settings.autoRename) {
      let queued = /* @__PURE__ */ new Set();
      for (let item of state.queue.values()) queued.add(item.url);
      fresh = urls.filter((u) => !queued.has(u)), skippedQueueCount = urls.length - fresh.length;
    }
    if (fresh.length === 0)
      return log(`All ${urls.length} pasted URL(s) are already in the queue.`, "warn"), { added: 0, skippedQueue: skippedQueueCount, skippedHistory: 0, total: urls.length };
    let dupes = [];
    if (!state.settings.autoRename)
      try {
        dupes = await findDuplicateUrls(fresh);
      } catch (err) {
        log(`Dedup check failed (continuing): ${err instanceof Error ? err.message : String(err)}`, "error");
      }
    let dupSet = new Set(dupes);
    for (let d of dupes)
      log(`Already downloaded previously, skipping duplicate: ${d}`, "warn");
    let toEnqueue = fresh.filter((u) => !dupSet.has(u));
    for (let u of toEnqueue)
      await enqueue(u);
    if (toEnqueue.length > 0) {
      let input = el("ad-url-input");
      input && (input.value = ""), updateChips();
    }
    return {
      added: toEnqueue.length,
      skippedQueue: skippedQueueCount,
      skippedHistory: dupes.length,
      total: urls.length
    };
  }
  async function enqueue(url, startNow = state.settings.autoStart) {
    if (!state.toolAvailable) {
      log("aria2 engine not installed - install it from the tab banner first.", "error"), setToolBanner(!1, state.toolVersion, defaultBannerText());
      return;
    }
    if (!state.settings.outputDir) {
      log("Choose an output directory first (Browse).", "error");
      return;
    }
    let filename = filenameFromUrl(url, state.queue.size + 1), requestedPath = joinPath(state.settings.outputDir, filename), jobId = typeof crypto != "undefined" && crypto.randomUUID ? crypto.randomUUID() : `job_${Date.now()}_${Math.random().toString(36).slice(2)}`, outputPath = requestedPath;
    try {
      outputPath = await resolveOutputPath(jobId, requestedPath, state.settings.autoRename);
    } catch (err) {
      log(`Output path resolve failed: ${err instanceof Error ? err.message : String(err)}`, "error");
    }
    let displayName = outputPath.split(/[\\/]/).pop() || filename, item = {
      jobId,
      url,
      filename: displayName,
      outputPath,
      status: "queued",
      percent: 0,
      downloadedBytes: 0,
      totalBytes: null,
      speedBps: 0,
      etaSecs: null,
      connections: 0,
      error: null,
      logs: [],
      logIndex: 0,
      command: null,
      engine: ARIA2_TOOL,
      startedAt: Date.now(),
      completedAt: null
    };
    state.queue.set(jobId, item), renderQueue(), startNow ? await startQueuedItem(jobId) : log(`Queued (paused): ${displayName}`, "info");
  }
  async function startQueuedItem(jobId) {
    let it = state.queue.get(jobId);
    if (it) {
      if (!state.toolAvailable) {
        log("aria2 engine not installed - install it from the tab banner first.", "error"), setToolBanner(!1, state.toolVersion, defaultBannerText());
        return;
      }
      if (!state.settings.outputDir) {
        log("Choose an output directory first (Browse).", "error");
        return;
      }
      it.status = "running", renderQueue();
      try {
        await downloadStart({
          engine: ARIA2_TOOL,
          url: it.url,
          output_path: it.outputPath,
          job_id: it.jobId,
          max_connections: state.settings.connections,
          speed_limit_kb: state.settings.speedLimitKb > 0 ? state.settings.speedLimitKb : void 0,
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Project Curator",
          max_tries: state.settings.maxTries,
          auto_rename: state.settings.autoRename
        });
      } catch (err) {
        it.status = "failed", it.error = err instanceof Error ? err.message : String(err), renderQueue(), log(`Start failed for ${it.url}: ${it.error}`, "error");
        return;
      }
      log(`Queued: ${it.filename}`, "info"), startPoll(jobId);
    }
  }
  async function startAllQueued() {
    let queued = [...state.queue.values()].filter((i) => i.status === "queued");
    queued.length !== 0 && (log(`Starting ${queued.length} queued download(s)...`, "info"), await Promise.all(queued.map((i) => startQueuedItem(i.jobId))));
  }
  function startPoll(jobId) {
    state.queue.get(jobId) && pollServiceProgress({
      intervalMs: 600,
      fetch: async () => {
        try {
          return await downloadProgress(jobId);
        } catch (e) {
          return;
        }
      },
      isRunning: (p) => p.running,
      onTick: (p) => {
        let it = state.queue.get(jobId);
        if (it) {
          if (it.percent = p.percent, it.downloadedBytes = p.downloadedBytes, it.totalBytes = p.totalBytes, it.speedBps = p.speedBps, it.etaSecs = p.etaSecs, it.connections = p.connections, it.error = p.error, it.command = p.command, it.engine = p.engine, isAbsolutePath(p.outputPath)) {
            it.outputPath = p.outputPath;
            let canonical = p.outputPath.split(/[\\/]/).pop();
            canonical && (it.filename = canonical);
          }
          p.logs.length > 0 && (it.logs = p.logs), appendLogDelta(it), renderQueueThrottled();
        }
      },
      onComplete: (ok, last) => finalize(jobId, ok, last)
    });
  }
  function finalize(jobId, ok, last) {
    var _a;
    let it = state.queue.get(jobId);
    if (!it) return;
    if (last) {
      if (it.percent = last.percent, it.downloadedBytes = last.downloadedBytes, it.totalBytes = last.totalBytes, it.speedBps = last.speedBps, it.error = last.error, last.outputPath && isAbsolutePath(last.outputPath)) {
        it.outputPath = last.outputPath;
        let canonical = last.outputPath.split(/[\\/]/).pop();
        canonical && (it.filename = canonical);
      }
      last.logs.length > 0 && (it.logs = last.logs);
    }
    appendLogDelta(it);
    let status = last == null ? void 0 : last.status, final;
    status === "cancelled" ? final = "cancelled" : status === "failed" || last != null && last.error || !ok ? final = "failed" : final = "completed", it.status = final, it.completedAt = Date.now(), renderQueue(), renderQueueThrottled();
    let finished = (_a = last == null ? void 0 : last.status) != null ? _a : ok ? "completed" : "failed";
    log(
      `${final.toUpperCase()} ${it.filename} - ${formatBytes(it.downloadedBytes)} in ${formatDuration(it.startedAt, it.completedAt)}` + (it.error ? ` (${it.error})` : ""),
      final === "completed" ? "success" : "error"
    ), final === "completed" && recordFinished(it);
  }
  async function recordFinished(it) {
    var _a;
    try {
      if (!isAbsolutePath(it.outputPath)) {
        log(`History skipped: no valid output path for ${it.filename}`, "error");
        return;
      }
      await ensureHistorySchema(), await recordDownload({
        url: it.url,
        normalized_url: it.url,
        // Canonical name: the basename of the resolved file on disk, so an
        // auto-renamed download (e.g. `file_1.jpg`) is shown under its real name
        // rather than the URL-derived one.
        filename: it.outputPath.split(/[\\/]/).pop() || it.filename,
        file_path: it.outputPath,
        file_size: it.downloadedBytes,
        status: it.status,
        error_message: it.error,
        completed_at: Math.floor(((_a = it.completedAt) != null ? _a : Date.now()) / 1e3),
        package_name: null
      }), await refreshHistoryUI("");
    } catch (err) {
      log(`History record failed: ${err instanceof Error ? err.message : String(err)}`, "error");
    }
  }
  async function retryDownload(jobId) {
    let it = state.queue.get(jobId);
    it && (state.queue.delete(jobId), renderQueue(), log(`Retrying: ${it.filename}`, "info"), await enqueue(it.url, !0));
  }
  async function redownloadUrl(url) {
    await enqueue(url);
  }
  async function cancelDownload(jobId) {
    try {
      await downloadCancel(jobId), log("Cancel requested.", "info");
    } catch (err) {
      log(`Cancel failed: ${err instanceof Error ? err.message : String(err)}`, "error");
    }
  }
  function renderQueue(listEl) {
    let list = listEl != null ? listEl : el("ad-queue-list");
    if (!list) return;
    list.innerHTML = "";
    let items = [...state.queue.values()].filter(
      (i) => !queueStatusFilter || i.status === queueStatusFilter
    );
    if (items.length === 0)
      list.innerHTML = queueStatusFilter ? '<div class="ad-empty">No queued items with this status.</div>' : '<div class="ad-empty">No downloads in queue.</div>';
    else {
      let table = document.createElement("table");
      table.className = "ad-table";
      let thead = document.createElement("thead");
      thead.innerHTML = '<tr><th class="col-status">Status</th><th class="col-hoster">Hoster</th><th class="col-file">File</th><th class="col-progress">Progress</th><th class="col-size">Size</th><th class="col-speed">Speed</th><th class="col-eta">ETA</th><th class="col-actions">Actions</th></tr>', table.appendChild(thead);
      let tbody = document.createElement("tbody");
      for (let item of items)
        tbody.appendChild(renderQueueRow(item));
      table.appendChild(tbody), list.appendChild(table);
    }
    applyColumnWidths();
    let count = el("ad-queue-count");
    count && (count.textContent = state.queue.size ? `(${state.queue.size})` : "");
  }
  function renderQueueRow(item) {
    let tr = document.createElement("tr");
    tr.className = "ad-table-row";
    let tdStatus = document.createElement("td");
    tdStatus.className = "col-status";
    let statusBadge = document.createElement("span");
    statusBadge.className = `ad-badge ${item.status}`, statusBadge.textContent = item.status, tdStatus.appendChild(statusBadge);
    let tdFile = document.createElement("td");
    tdFile.className = "col-file";
    let name = document.createElement("div");
    name.className = "ad-row-mono", name.textContent = item.filename, name.title = item.url;
    let url = document.createElement("div");
    if (url.className = "ad-meta", url.textContent = item.url, url.style.cssText = "display:block;width:100%;", tdFile.appendChild(name), tdFile.appendChild(url), (item.status === "failed" || item.status === "cancelled") && item.error) {
      let err = document.createElement("div");
      err.className = "ad-error", err.textContent = item.error, tdFile.appendChild(err);
    }
    let tdProgress = document.createElement("td");
    tdProgress.className = "col-progress";
    let progressWrap = document.createElement("div");
    progressWrap.className = "ad-progress-wrap";
    let bar = document.createElement("div");
    bar.className = "ad-progress";
    let fill = document.createElement("div");
    fill.className = "ad-progress-fill", fill.style.width = `${Math.max(0, Math.min(100, item.percent))}%`, bar.appendChild(fill);
    let pct = document.createElement("span");
    pct.className = "ad-meta", pct.textContent = `${Math.round(item.percent)}%`, progressWrap.appendChild(bar), progressWrap.appendChild(pct), tdProgress.appendChild(progressWrap);
    let tdHoster = document.createElement("td");
    tdHoster.className = "col-hoster";
    let hoster = document.createElement("span");
    hoster.className = "ad-meta", hoster.style.cssText = "display:block;width:100%;", hoster.textContent = hostFromUrl(item.url), hoster.title = item.url, tdHoster.appendChild(hoster);
    let tdSize = document.createElement("td");
    tdSize.className = "col-size";
    let size = document.createElement("span");
    size.className = "ad-meta", size.style.cssText = "display:block;width:100%;";
    let total = item.totalBytes ? ` / ${formatBytes(item.totalBytes)}` : "";
    size.textContent = `${formatBytes(item.downloadedBytes)}${total}`, tdSize.appendChild(size);
    let running = item.status === "running", tdSpeed = document.createElement("td");
    tdSpeed.className = "col-speed";
    let speed = document.createElement("span");
    speed.className = "ad-meta", speed.style.cssText = "display:block;width:100%;", speed.textContent = running ? formatRate(item.speedBps) : "\u2014", tdSpeed.appendChild(speed);
    let tdEta = document.createElement("td");
    tdEta.className = "col-eta";
    let eta = document.createElement("span");
    eta.className = "ad-meta", eta.style.cssText = "display:block;width:100%;", eta.textContent = running ? formatEta(item.etaSecs) : "\u2014", tdEta.appendChild(eta);
    let tdActions = document.createElement("td");
    tdActions.className = "col-actions";
    let actions = document.createElement("div");
    actions.style.cssText = "display:flex;gap:4px;justify-content:flex-end;";
    let mk = (icon, title, fn) => {
      let b = document.createElement("button");
      b.type = "button", b.className = "win-button", b.style.cssText = "font-size:10px;padding:1px 6px;", b.innerHTML = `<i class="${icon}"></i>`, b.title = title, b.addEventListener("click", fn), actions.appendChild(b);
    };
    return item.status === "queued" && mk("bi bi-play-fill", "Start", () => void startQueuedItem(item.jobId)), item.status === "running" && mk("bi bi-stop-circle", "Cancel (graceful)", () => void cancelDownload(item.jobId)), item.status === "completed" && mk("bi bi-folder2-open", "Reveal in Explorer", () => {
      (async () => {
        var _a;
        let api = (_a = window.__TAURI__) == null ? void 0 : _a.core;
        if (api != null && api.invoke)
          try {
            await api.invoke("reveal_in_folder", { path: item.outputPath });
          } catch (e) {
            log("Could not reveal output file.", "error");
          }
      })();
    }), (item.status === "failed" || item.status === "cancelled") && mk("bi bi-arrow-clockwise", "Retry", () => void retryDownload(item.jobId)), mk("bi bi-clipboard", "Copy URL", () => {
      var _a;
      return void ((_a = navigator.clipboard) == null ? void 0 : _a.writeText(item.url));
    }), tdActions.appendChild(actions), tr.appendChild(tdStatus), tr.appendChild(tdHoster), tr.appendChild(tdFile), tr.appendChild(tdProgress), tr.appendChild(tdSize), tr.appendChild(tdSpeed), tr.appendChild(tdEta), tr.appendChild(tdActions), tr;
  }

  // aria2-downloader/src/history-view.ts
  async function initHistory() {
    await ensureHistorySchema(), await refreshHistoryUI("");
  }
  async function refreshHistoryUI(term) {
    try {
      state.history = term.trim() ? await searchHistory(term.trim()) : await queryHistory(200);
    } catch (err) {
      log(`History load failed: ${err instanceof Error ? err.message : String(err)}`, "error");
      return;
    }
    renderHistory(state.history);
  }
  async function removeHistoryRecord(id) {
    try {
      await removeHistoryEntry(id), state.history = state.history.filter((r) => r.id !== id), renderHistory(state.history), log("Removed history entry.", "info");
    } catch (err) {
      log(`Remove failed: ${err instanceof Error ? err.message : String(err)}`, "error");
    }
  }
  function renderHistory(records, listEl) {
    let list = listEl != null ? listEl : el("ad-history-list");
    if (!list) return;
    if (list.innerHTML = "", !records.length) {
      list.innerHTML = '<div class="ad-empty">No downloads recorded yet.</div>';
      return;
    }
    let table = document.createElement("table");
    table.className = "ad-table";
    let thead = document.createElement("thead");
    thead.innerHTML = '<tr><th class="col-status">Status</th><th class="col-hoster">Hoster</th><th class="col-file">File</th><th class="col-size">Size</th><th class="col-hdate">Completed</th><th class="col-actions">Actions</th></tr>', table.appendChild(thead);
    let tbody = document.createElement("tbody");
    for (let rec of records)
      tbody.appendChild(renderHistoryRow(rec));
    table.appendChild(tbody), list.appendChild(table), applyColumnWidths();
  }
  function renderHistoryRow(rec) {
    let tr = document.createElement("tr");
    tr.className = "ad-table-row";
    let tdStatus = document.createElement("td");
    tdStatus.className = "col-status";
    let badge = document.createElement("span");
    badge.className = `ad-badge ${rec.status}`, badge.textContent = rec.status, tdStatus.appendChild(badge);
    let tdHoster = document.createElement("td");
    tdHoster.className = "col-hoster";
    let hoster = document.createElement("span");
    hoster.className = "ad-meta", hoster.style.cssText = "display:block;width:100%;", hoster.textContent = hostFromUrl(rec.url), hoster.title = rec.url, tdHoster.appendChild(hoster);
    let tdFile = document.createElement("td");
    tdFile.className = "col-file";
    let name = document.createElement("div");
    name.className = "ad-row-mono", name.textContent = rec.filename, name.title = rec.file_path, tdFile.appendChild(name);
    let tdSize = document.createElement("td");
    tdSize.className = "col-size";
    let size = document.createElement("span");
    size.className = "ad-meta", size.style.cssText = "display:block;width:100%;", size.textContent = formatBytes(rec.file_size), tdSize.appendChild(size);
    let tdDate = document.createElement("td");
    tdDate.className = "col-hdate";
    let date = document.createElement("span");
    date.className = "ad-meta", date.style.cssText = "display:block;width:100%;", date.textContent = formatDateTime(rec.completed_at), tdDate.appendChild(date);
    let tdActions = document.createElement("td");
    tdActions.className = "col-actions";
    let actions = document.createElement("div");
    actions.style.cssText = "display:flex;gap:4px;justify-content:flex-end;";
    let mk = (icon, title, fn) => {
      let b = document.createElement("button");
      b.type = "button", b.className = "win-button", b.style.cssText = "font-size:10px;padding:1px 6px;", b.innerHTML = `<i class="${icon}"></i>`, b.title = title, b.addEventListener("click", fn), actions.appendChild(b);
    };
    return mk("bi bi-folder2-open", "Open in Explorer (highlight)", () => {
      (async () => await revealInFolder(rec.file_path) || log("Could not reveal output file in Explorer.", "error"))();
    }), mk("bi bi-clipboard", "Copy path", () => {
      var _a;
      return void ((_a = navigator.clipboard) == null ? void 0 : _a.writeText(rec.file_path));
    }), mk("bi bi-link-45deg", "Copy URL", () => {
      var _a;
      return void ((_a = navigator.clipboard) == null ? void 0 : _a.writeText(rec.url));
    }), mk("bi bi-arrow-repeat", "Re-download", () => void redownloadUrl(rec.url)), mk("bi bi-x-lg", "Remove from history", () => void removeHistoryRecord(rec.id)), tdActions.appendChild(actions), tr.appendChild(tdStatus), tr.appendChild(tdHoster), tr.appendChild(tdFile), tr.appendChild(tdSize), tr.appendChild(tdDate), tr.appendChild(tdActions), tr;
  }

  // aria2-downloader/src/ui.ts
  function buildWorkspaceRoot() {
    var _a, _b, _c, _d, _e, _f, _g;
    injectStyles();
    let root = document.createElement("div");
    root.className = "ad-workspace";
    let banner = document.createElement("div");
    banner.id = "ad-banner", banner.className = "ad-banner", banner.innerHTML = `
    <i class="bi bi-exclamation-triangle-fill" style="flex-shrink:0;font-size:13px;"></i>
    <div class="ad-banner-inner">
      <div id="ad-banner-text"></div>
      <div class="ad-banner-status" id="ad-banner-status" style="display:none;">Preparing install...</div>
      <div class="ad-banner-progress" id="ad-banner-progress" style="display:none;">
        <div class="ad-banner-fill" id="ad-banner-fill"></div>
      </div>
    </div>
    <button type="button" class="win-button primary" id="ad-install-btn" style="margin-left:8px;font-size:10px;flex-shrink:0;">
      <i class="bi bi-download"></i> Download &amp; Install
    </button>`, root.appendChild(banner);
    let topBar = document.createElement("div");
    topBar.className = "group-box ad-toolbar", topBar.innerHTML = `
    <div class="group-box-title"><i class="bi bi-link-45deg"></i> Add Downloads</div>
    <div class="ad-toolbar-row">
      <textarea id="ad-url-input" class="input-field ad-url-input" placeholder="Paste download URLs (comma, space, or newline separated)..."></textarea>
      <div style="display:flex;flex-direction:column;gap:6px;">
        <button type="button" class="win-button primary" id="ad-add-btn" style="font-size:11px;"><i class="bi bi-plus-circle"></i> Add to Queue</button>
        <button type="button" class="win-button" id="ad-clear-input-btn" style="font-size:11px;"><i class="bi bi-eraser"></i> Clear</button>
      </div>
    </div>
    <div class="ad-chips" id="ad-chips"></div>
    <div id="ad-add-feedback" style="display:none;font-size:11px;padding:5px 8px;margin-top:6px;border:1px solid var(--sys-border-dark,#999);border-radius:2px;background:var(--sys-window-bg,#fff);"></div>
    <div class="ad-summary-row">
      <label for="ad-output-dir">Output</label>
      <input type="text" id="ad-output-dir" class="input-field" readonly style="flex:1;font-size:11px;" />
      <button type="button" class="win-button" id="ad-browse-btn" style="font-size:10px;"><i class="bi bi-folder2-open"></i> Browse</button>
      <button type="button" class="win-button" id="ad-open-folder-btn" style="font-size:10px;"><i class="bi bi-folder"></i> Open</button>
    </div>
    <div class="ad-summary-row">
      <label for="ad-conns">Connections</label>
      <input type="number" id="ad-conns" min="1" max="16" value="${state.settings.connections}" />
      <label for="ad-speed">Speed (KiB/s, 0=\u221E)</label>
      <input type="number" id="ad-speed" min="0" value="${state.settings.speedLimitKb}" />
      <label for="ad-tries">Max tries</label>
      <input type="number" id="ad-tries" min="0" value="${state.settings.maxTries}" />
    </div>
    <div class="ad-summary-row">
      <label class="ad-toggle"><input type="checkbox" id="ad-auto-rename" ${state.settings.autoRename ? "checked" : ""} /> Rename if exists (<span style="font-family:'Consolas',monospace;">_1</span>, <span style="font-family:'Consolas',monospace;">_2</span>, ...)</label>
      <label class="ad-toggle"><input type="checkbox" id="ad-auto-start" ${state.settings.autoStart ? "checked" : ""} /> Auto start queue</label>
    </div>`, root.appendChild(topBar);
    let middle = document.createElement("div");
    middle.className = "ad-middle", middle.innerHTML = `
    <div class="ad-column ad-queue-box">
      <div class="group-box" style="flex:1;display:flex;flex-direction:column;min-height:0;">
        <div class="group-box-title"><i class="bi bi-list-ul"></i> Download Queue <span id="ad-queue-count" style="color:#888;font-size:10px;"></span>
        </div>
        <div class="ad-toolbar-row" style="margin-top:0;" id="ad-queue-filter">
          <button type="button" class="win-button" id="ad-start-all-btn" style="font-size:10px;"><i class="bi bi-play-fill"></i> Start All</button>
          <button type="button" class="win-button ad-filter-btn active" data-status="">All</button>
          <button type="button" class="win-button ad-filter-btn" data-status="queued">Queued</button>
          <button type="button" class="win-button ad-filter-btn" data-status="running">Running</button>
          <button type="button" class="win-button ad-filter-btn" data-status="completed">Completed</button>
          <button type="button" class="win-button ad-filter-btn" data-status="failed">Failed</button>
          <button type="button" class="win-button ad-filter-btn" data-status="cancelled">Cancelled</button>
        </div>
        <div class="ad-scroll" id="ad-queue-list"></div>
      </div>
    </div>
    <div class="ad-column ad-history-box">
      <div class="group-box" style="flex:1;display:flex;flex-direction:column;min-height:0;">
        <div class="group-box-title"><i class="bi bi-clock-history"></i> History</div>
        <div class="ad-toolbar-row" style="margin-top:0;">
          <input type="text" id="ad-history-search" class="input-field" placeholder="Search history..." style="flex:1;font-size:11px;" />
          <button type="button" class="win-button" id="ad-history-refresh" style="font-size:10px;"><i class="bi bi-arrow-clockwise"></i></button>
        </div>
        <div class="ad-scroll" id="ad-history-list" style="margin-top:4px;"></div>
      </div>
    </div>`, root.appendChild(middle);
    let queueList = middle.querySelector("#ad-queue-list"), historyList = middle.querySelector("#ad-history-list"), logDock = document.createElement("div");
    logDock.className = "group-box ad-log-dock", logDock.innerHTML = `
    <div class="group-box-title" style="display:flex;align-items:center;justify-content:space-between;">
      <span><i class="bi bi-terminal"></i> Activity Log</span>
      <button type="button" class="win-button" id="ad-log-clear-btn" style="font-size:10px;padding:0 5px;height:18px;line-height:18px;"><i class="bi bi-trash3"></i> Clear</button>
    </div>
    <div class="ad-log-box" id="ad-log"></div>`, root.appendChild(logDock);
    let showFeedback = (html, isError) => {
      let fb = root.querySelector("#ad-add-feedback");
      fb && (fb.innerHTML = html, fb.style.display = "block", fb.style.color = isError ? "var(--sys-error-text, #c00)" : "var(--sys-window-text, #333)", fb.style.borderColor = isError ? "var(--sys-error-text, #c00)" : "var(--sys-border-dark, #999)", fb.style.background = isError ? "rgba(255, 0, 0, 0.05)" : "rgba(0, 128, 0, 0.05)");
    }, clearFeedback = () => {
      let fb = root.querySelector("#ad-add-feedback");
      fb && (fb.style.display = "none", fb.innerHTML = "");
    };
    (_a = root.querySelector("#ad-log-clear-btn")) == null || _a.addEventListener("click", () => clearLogDock()), (_b = root.querySelector("#ad-install-btn")) == null || _b.addEventListener("click", () => void installAria2(banner)), (_c = root.querySelector("#ad-add-btn")) == null || _c.addEventListener("click", async () => {
      let ta = root.querySelector("#ad-url-input");
      if (!ta || !ta.value.trim()) return;
      clearFeedback();
      let res = await addUrls(ta.value);
      if (res.added > 0) {
        ta.value = "", updateChips();
        let msg = `<i class="bi bi-check-circle"></i> Added <b>${res.added}</b> URL(s) to queue.`;
        res.skippedHistory > 0 && (msg += ` (${res.skippedHistory} duplicate(s) already in history skipped)`), res.skippedQueue > 0 && (msg += ` (${res.skippedQueue} already in queue skipped)`), showFeedback(msg, !1), log(`Added ${res.added} URL(s) to queue.`, "info"), state.settings.autoStart && startAllQueued();
      } else
        res.skippedHistory > 0 ? (showFeedback(
          `<i class="bi bi-exclamation-triangle"></i> Rejected: <b>${res.skippedHistory}</b> URL(s) were already downloaded previously.<br/><span style="opacity:0.85;font-size:10px;">Enable <i>"Rename if exists (_1, _2, ...)"</i> below if you wish to download duplicate copies.</span>`,
          !0
        ), log(`Rejected: ${res.skippedHistory} URL(s) were already downloaded previously. Enable "Rename if exists" to download duplicates.`, "warn")) : res.skippedQueue > 0 ? (showFeedback(
          `<i class="bi bi-info-circle"></i> <b>${res.skippedQueue}</b> URL(s) are already present in the active download queue.`,
          !0
        ), log(`Rejected: ${res.skippedQueue} URL(s) are already in the queue.`, "warn")) : showFeedback('<i class="bi bi-x-circle"></i> No valid URLs found to download.', !0);
    }), (_d = root.querySelector("#ad-clear-input-btn")) == null || _d.addEventListener("click", () => {
      let ta = root.querySelector("#ad-url-input");
      ta && (ta.value = ""), clearFeedback(), updateChips();
    }), (_e = root.querySelector("#ad-url-input")) == null || _e.addEventListener("input", () => {
      clearFeedback(), updateChips();
    });
    let outInput = root.querySelector("#ad-output-dir");
    outInput && (outInput.value = state.settings.outputDir), (_f = root.querySelector("#ad-browse-btn")) == null || _f.addEventListener("click", async () => {
      let picked = await pickDirectory();
      picked && (state.settings.outputDir = picked, savePersisted("aria2-downloader-output-dir", picked), outInput && (outInput.value = picked), log("Output directory set: " + picked, "info"));
    }), (_g = root.querySelector("#ad-open-folder-btn")) == null || _g.addEventListener("click", async () => {
      let dir = state.settings.outputDir;
      if (dir)
        try {
          await PH5.callService("OpenFolder", { path: dir });
        } catch (e) {
          window.open("file://" + dir.replace(/\\/g, "/"));
        }
    });
    let conns = root.querySelector("#ad-conns");
    conns && (conns.value = String(state.settings.connections), conns.addEventListener("change", () => {
      state.settings.connections = clampNum(parseInt(conns.value, 10), 1, 16, 4), conns.value = String(state.settings.connections), savePersisted("aria2-downloader-connections", String(state.settings.connections));
    }));
    let speed = root.querySelector("#ad-speed");
    speed && (speed.value = String(state.settings.speedLimitKb), speed.addEventListener("change", () => {
      state.settings.speedLimitKb = Math.max(0, parseInt(speed.value, 10) || 0), speed.value = String(state.settings.speedLimitKb), savePersisted("aria2-downloader-speed-limit", String(state.settings.speedLimitKb));
    }));
    let tries = root.querySelector("#ad-tries");
    tries && (tries.value = String(state.settings.maxTries), tries.addEventListener("change", () => {
      state.settings.maxTries = Math.max(0, parseInt(tries.value, 10) || 0), tries.value = String(state.settings.maxTries), savePersisted("aria2-downloader-max-tries", String(state.settings.maxTries));
    }));
    let autoRename = root.querySelector("#ad-auto-rename");
    autoRename && (autoRename.checked = state.settings.autoRename, autoRename.addEventListener("change", () => {
      state.settings.autoRename = autoRename.checked, savePersisted("aria2-downloader-auto-rename", autoRename.checked ? "1" : "0");
    }));
    let autoStart = root.querySelector("#ad-auto-start");
    autoStart && (autoStart.checked = state.settings.autoStart, autoStart.addEventListener("change", () => {
      state.settings.autoStart = autoStart.checked, savePersisted("aria2-downloader-auto-start", autoStart.checked ? "1" : "0");
    }));
    let startAllBtn = root.querySelector("#ad-start-all-btn");
    startAllBtn && startAllBtn.addEventListener("click", () => void startAllQueued());
    let queueFilterEls = root.querySelectorAll("#ad-queue-filter .ad-filter-btn");
    return queueFilterEls.forEach(
      (btn) => btn.addEventListener("click", () => {
        var _a2;
        setQueueStatusFilter((_a2 = btn.dataset.status) != null ? _a2 : ""), queueFilterEls.forEach((b) => b.classList.toggle("active", b === btn)), renderQueue();
      })
    ), wireColumnResize(), renderQueue(queueList), updateChips(), renderHistory(state.history, historyList), setToolBanner(state.toolAvailable, state.toolVersion, defaultBannerText(), banner), refreshToolStatus(banner), setTimeout(() => {
      refreshToolStatus(), initHistory();
    }, 50), root;
  }
  function renderTab() {
    return buildWorkspaceRoot();
  }
  async function bootstrap() {
    state.settings.outputDir = loadPersisted("aria2-downloader-output-dir", state.settings.outputDir) || state.settings.outputDir, state.settings.connections = clampNum(
      parseInt(loadPersisted("aria2-downloader-connections", String(state.settings.connections)), 10),
      1,
      16,
      state.settings.connections
    ), state.settings.speedLimitKb = Math.max(
      0,
      parseInt(loadPersisted("aria2-downloader-speed-limit", String(state.settings.speedLimitKb)), 10) || 0
    ), state.settings.maxTries = Math.max(
      0,
      parseInt(loadPersisted("aria2-downloader-max-tries", String(state.settings.maxTries)), 10) || 0
    ), state.settings.autoRename = loadPersisted("aria2-downloader-auto-rename", "0") === "1", state.settings.autoStart = loadPersisted("aria2-downloader-auto-start", "1") === "1", await refreshToolStatus(), await initHistory(), log("aria2-downloader ready.", "success");
  }

  // aria2-downloader/src/index.ts
  var PH7 = window.PluginHost;
  PH7 ? (PH7.registerTab(TAB_ID, "Aria2 Downloader", "bi bi-cloud-arrow-down", renderTab), (!PH7.isAutoloadEnabled || PH7.isAutoloadEnabled(TAB_ID)) && bootstrap(), console.log("aria2-downloader: registered tab.")) : console.error("aria2-downloader: PluginHost not available; aborting.");
})();
