[package]
name = "curator-media"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
turbojpeg = { workspace = true }
fast_image_resize = { workspace = true }
png = { workspace = true }
webp = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true }
curator-proto = { path = "../curator-proto" }

[dev-dependencies]
tempfile = "3"