// Build script: bundles each plugin's src/index.ts → index.js (IIFE)
// Usage:
//   node build.js --plugin <name>   build a single plugin
//   node build.js --all             build every plugin that has a src/ dir
//
// Plugins with no src/index.ts are silently skipped so existing single-file
// plugins keep working without changes.

"use strict";

const esbuild = require("esbuild");
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;

// ---------------------------------------------------------------------------
// CLI arg parsing
// ---------------------------------------------------------------------------
const args = process.argv.slice(2);
const allFlag = args.includes("--all");
const pluginIdx = args.indexOf("--plugin");
const pluginName = pluginIdx !== -1 ? args[pluginIdx + 1] : null;

if (!allFlag && !pluginName) {
  console.error("Usage: node build.js --plugin <name> | --all");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Build a single plugin
// ---------------------------------------------------------------------------
async function buildPlugin(name) {
  const srcEntry = path.join(ROOT, name, "src", "index.ts");

  if (!fs.existsSync(srcEntry)) {
    // Not yet migrated to multi-file — skip gracefully.
    return;
  }

  const outFile = path.join(ROOT, name, "index.js");

  try {
    await esbuild.build({
      entryPoints: [srcEntry],
      outfile: outFile,
      bundle: true,
      format: "iife",
      target: "es2017",
      platform: "browser",
      // Tree-shake dead code and minify whitespace but keep names readable
      // for easier debugging inside the app's DevTools.
      minifyWhitespace: false,
      minifyIdentifiers: false,
      minifySyntax: true,
      // Prepend a banner so it's clear the file is auto-generated.
      banner: {
        js: [
          "// ─────────────────────────────────────────────────────────────────────",
          `// AUTO-GENERATED by plugins/build.js — do not edit by hand.`,
          `// Source: plugins/${name}/src/`,
          "// ─────────────────────────────────────────────────────────────────────",
        ].join("\n"),
      },
      logLevel: "warning",
    });

    const stat = fs.statSync(outFile);
    const kb = (stat.size / 1024).toFixed(1);
    console.log(`✓  ${name}  →  index.js  (${kb} KB)`);
  } catch (err) {
    // esbuild prints its own formatted error; we just surface the plugin name.
    console.error(`✗  ${name}: build failed (see errors above)`);
    process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// Discover all plugin directories
// ---------------------------------------------------------------------------
function discoverPlugins() {
  return fs
    .readdirSync(ROOT, { withFileTypes: true })
    .filter(
      (d) =>
        d.isDirectory() &&
        !d.name.startsWith(".") &&
        d.name !== "node_modules"
    )
    .map((d) => d.name);
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
async function main() {
  const targets = allFlag ? discoverPlugins() : [pluginName];
  for (const name of targets) {
    await buildPlugin(name);
  }
}

main().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
