// Watch script: rebuilds a plugin's src/ on any file change.
// Usage:
//   node watch.js --plugin <name>
//
// Ctrl-C to stop.

"use strict";

const esbuild = require("esbuild");
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;

const args = process.argv.slice(2);
const pluginIdx = args.indexOf("--plugin");
const pluginName = pluginIdx !== -1 ? args[pluginIdx + 1] : null;

if (!pluginName) {
  console.error("Usage: node watch.js --plugin <name>");
  process.exit(1);
}

const srcEntry = path.join(ROOT, pluginName, "src", "index.ts");
if (!fs.existsSync(srcEntry)) {
  console.error(`No src/index.ts found for plugin "${pluginName}". Has it been migrated yet?`);
  process.exit(1);
}

const outFile = path.join(ROOT, pluginName, "index.js");

async function main() {
  const ctx = await esbuild.context({
    entryPoints: [srcEntry],
    outfile: outFile,
    bundle: true,
    format: "iife",
    target: "es2017",
    platform: "browser",
    minifyWhitespace: false,
    minifyIdentifiers: false,
    minifySyntax: true,
    banner: {
      js: [
        "// ─────────────────────────────────────────────────────────────────────",
        `// AUTO-GENERATED by plugins/watch.js — do not edit by hand.`,
        `// Source: plugins/${pluginName}/src/`,
        "// ─────────────────────────────────────────────────────────────────────",
      ].join("\n"),
    },
    logLevel: "info",
    // Custom plugin to log rebuild timestamps
    plugins: [
      {
        name: "rebuild-notify",
        setup(build) {
          build.onEnd((result) => {
            const now = new Date().toLocaleTimeString();
            if (result.errors.length === 0) {
              const stat = fs.statSync(outFile);
              const kb = (stat.size / 1024).toFixed(1);
              console.log(`[${now}]  ✓  ${pluginName}  →  index.js  (${kb} KB)`);
            } else {
              console.log(`[${now}]  ✗  ${pluginName}: build errors (see above)`);
            }
          });
        },
      },
    ],
  });

  await ctx.watch();
  console.log(`Watching plugins/${pluginName}/src/ for changes… (Ctrl-C to stop)`);
}

main().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
