[package]
name = "curator-service"
version = "0.1.0"
edition = "2024"

[dependencies]
curator-core = { path = "../curator-core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { workspace = true }
clap = { workspace = true }
sha2 = "0.10"
bytemuck = "1"
sqlx = { workspace = true }
ureq = { workspace = true }
tonic = { workspace = true }
tokio-util = "0.7"
zip = { version = "2", default-features = false, features = ["deflate"] }
