export { execute, query } from "./client";
export type { Row } from "./client";
export { initDb } from "./schema";
export { getCached, getBatchCached, setCached, touchCached, deleteCached } from "./metadata.repo";
export {
  getFollowedSeries,
  getFollowedSeriesCount,
  getFollowedSeriesPage,
  getFollowedSeriesRow,
  followSeries,
  unfollowSeries,
  getReadingProgress,
  setReadingProgress,
  getProgressForSeries,
  addHistory,
  removeHistory,
  clearHistory,
  getHistory,
  getHistoryCount,
  getHistoryPage,
  getHistoryPermalinks,
  getBookmarks,
  getBookmarkCount,
  getBookmarksPage,
  getBookmark,
  getBookmarkPermalinks,
  addBookmark,
  removeBookmark,
} from "./library.repo";
export {
  getCachedPages,
  setCachedPage,
  countCachedPages,
  getCachedPageCounts,
  getCacheOverviewStats,
  getCachedSeriesGroups,
  clearCachedGroupPages,
  clearAllCachedPages,
  clearAllCachedCovers,
  clearAllCacheStorage,
} from "./cache.repo";
export type {
  CachedMetadata,
  FollowedSeriesRow,
  FollowedSeriesPageResult,
  ReadingProgressRow,
  SeriesProgressRow,
  HistoryRow,
  HistoryPageResult,
  BookmarkRow,
  BookmarkPageResult,
  CachedPageRow,
  ChapterCacheCount,
  CacheOverviewStats,
  CachedSeriesGroup,
} from "../types/db";