// ─────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by plugins/build.js — do not edit by hand.
// Source: plugins/image-compare/src/
// ─────────────────────────────────────────────────────────────────────
"use strict";
(() => {
  // image-compare/src/state.ts
  var TAB_ID = "image-compare", state = {
    mode: "side-by-side",
    splitPos: 50,
    onionOpacity: 50,
    syncLock: !0,
    pinSplitterToImage: !1,
    showInfoOverlay: !0,
    zoomA: 1,
    panA: { x: 0, y: 0 },
    zoomB: 1,
    panB: { x: 0, y: 0 },
    slotA: { id: null, path: "", url: "", name: "Image A", width: 0, height: 0, sizeStr: "" },
    slotB: { id: null, path: "", url: "", name: "Image B", width: 0, height: 0, sizeStr: "" },
    isDraggingPan: !1,
    dragTargetSlot: "both",
    panStartX: 0,
    panStartY: 0,
    panInitialA: { x: 0, y: 0 },
    panInitialB: { x: 0, y: 0 },
    isDraggingSlider: !1,
    rafPending: !1,
    globalEventsBound: !1
  };

  // lib/format.ts
  function formatBytes(bytes, fallback = "", decimals = 2) {
    var _a;
    if (bytes == null || isNaN(bytes) || bytes < 0) return fallback;
    if (bytes === 0) return "0 B";
    let units = ["B", "KB", "MB", "GB", "TB"], i = Math.floor(Math.log(bytes) / Math.log(1024));
    return `${(bytes / Math.pow(1024, i)).toFixed(decimals)} ${(_a = units[i]) != null ? _a : "B"}`;
  }

  // lib/ipc-utils.ts
  var PH = window.PluginHost;

  // lib/navigation.ts
  function navigateToTab(tabId) {
    let item = document.querySelector(
      `.nav-item[data-view="extensions-${tabId}"]`
    );
    item && item.click();
  }
  function closeInfoModal() {
    var _a;
    if ((_a = window.PluginHost) != null && _a.closeImageViewer)
      window.PluginHost.closeImageViewer();
    else {
      let viewerModal = document.getElementById("image-viewer-modal");
      viewerModal != null && viewerModal.classList.contains("active") && viewerModal.classList.remove("active");
    }
    let modal = document.getElementById("image-info-modal");
    if (!(modal != null && modal.classList.contains("active"))) return;
    let closeBtn = modal.querySelector(".modal-close");
    closeBtn ? closeBtn.click() : modal.classList.remove("active");
  }

  // lib/drop-zone.ts
  var boundTabs = /* @__PURE__ */ new Set();
  function setupDropZone(tabId, dropZoneIds, onFiles) {
    var _a;
    let api = window.__TAURI__;
    if (!((_a = api == null ? void 0 : api.webview) != null && _a.getCurrentWebview) || boundTabs.has(tabId)) return;
    boundTabs.add(tabId);
    let ids = Array.isArray(dropZoneIds) ? dropZoneIds : [dropZoneIds];
    api.webview.getCurrentWebview().onDragDropEvent((event) => {
      var _a2, _b, _c;
      let tabEl = document.getElementById(`view-extensions-${tabId}`);
      if (!(tabEl != null && tabEl.classList.contains("active"))) return;
      let drop = event.payload, getHitZoneId = () => {
        let pos = drop.position;
        if (!pos || typeof pos.x != "number") return null;
        let cx = pos.x / window.devicePixelRatio, cy = pos.y / window.devicePixelRatio, hit = document.elementFromPoint(cx, cy);
        if (!hit) return null;
        for (let id of ids) {
          let zone = document.getElementById(id);
          if (zone && (zone === hit || zone.contains(hit))) return id;
        }
        return null;
      };
      if (drop.type === "enter" || drop.type === "over") {
        let hitId = getHitZoneId();
        for (let id of ids) {
          let zone = document.getElementById(id);
          zone && (id === hitId ? zone.classList.add("toolbox-drop-active") : zone.classList.remove("toolbox-drop-active"));
        }
      } else if (drop.type === "leave")
        for (let id of ids)
          (_a2 = document.getElementById(id)) == null || _a2.classList.remove("toolbox-drop-active");
      else if (drop.type === "drop") {
        let hitId = getHitZoneId();
        for (let id of ids)
          (_b = document.getElementById(id)) == null || _b.classList.remove("toolbox-drop-active");
        let paths = (_c = drop.paths) != null ? _c : [];
        paths.length > 0 && onFiles(paths, hitId);
      }
    });
  }

  // lib/poll.ts
  var PH2 = window.PluginHost;

  // image-compare/src/ui.ts
  var PH3 = window.PluginHost;
  function el(id) {
    return document.getElementById(id);
  }
  var navigateToTab2 = () => navigateToTab(TAB_ID);
  function getAssetSrc(path) {
    return path ? path.startsWith("blob:") || path.startsWith("data:") || path.startsWith("http://") || path.startsWith("https://") ? path : PH3.convertFileSrc(path) : "";
  }
  function loadImageMetadata(slot, callback) {
    if (!slot.url) {
      slot.width = 0, slot.height = 0, callback && callback();
      return;
    }
    let img = new Image();
    img.onload = () => {
      slot.width = img.naturalWidth, slot.height = img.naturalHeight, callback && callback();
    }, img.onerror = (err) => {
      console.error("Image Compare: failed to load image src:", slot.path, err), callback && callback();
    }, img.src = slot.url;
  }
  function loadAssetIntoSlot(targetSlot, assetContext, fileObj) {
    let slotObj = targetSlot === "A" ? state.slotA : state.slotB;
    if (fileObj) {
      slotObj.id = null;
      let filePath = fileObj.path || "";
      slotObj.path = filePath || fileObj.name, filePath ? slotObj.url = getAssetSrc(filePath) : slotObj.url = URL.createObjectURL(fileObj), slotObj.name = fileObj.name, slotObj.sizeStr = formatBytes(fileObj.size);
    } else assetContext && (slotObj.id = assetContext.asset_id || null, slotObj.path = assetContext.path || "", slotObj.name = assetContext.path ? assetContext.path.split(/[\\/]/).pop() : "Asset #" + assetContext.asset_id, slotObj.url = getAssetSrc(slotObj.path), slotObj.sizeStr = "");
    loadImageMetadata(slotObj, () => {
      updateSlotHeaders(), renderCanvasDOM();
    });
  }
  function swapSlots() {
    let temp = Object.assign({}, state.slotA);
    Object.assign(state.slotA, state.slotB), Object.assign(state.slotB, temp), updateSlotHeaders(), renderCanvasDOM();
  }
  function resetZoomAndPan() {
    state.zoomA = 1, state.panA = { x: 0, y: 0 }, state.zoomB = 1, state.panB = { x: 0, y: 0 }, scheduleTransformUpdate();
  }
  function fitToViewport() {
    state.zoomA = 1, state.panA = { x: 0, y: 0 }, state.zoomB = 1, state.panB = { x: 0, y: 0 }, scheduleTransformUpdate();
  }
  function scheduleTransformUpdate() {
    state.rafPending || (state.rafPending = !0, requestAnimationFrame(() => {
      state.rafPending = !1, applyTransforms();
    }));
  }
  function applyTransforms() {
    let clipVal = 100 - state.splitPos, container = el("compare-canvas-area"), rect = container ? container.getBoundingClientRect() : null;
    if (state.mode === "side-by-side") {
      let wrapperA = el("cmp-wrapper-a");
      wrapperA && (wrapperA.style.transform = `translate(${state.panA.x}px, ${state.panA.y}px) scale(${state.zoomA})`);
      let wrapperB = el("cmp-wrapper-b");
      if (wrapperB) {
        let activePan = state.syncLock ? state.panA : state.panB, activeZoom = state.syncLock ? state.zoomA : state.zoomB;
        wrapperB.style.transform = `translate(${activePan.x}px, ${activePan.y}px) scale(${activeZoom})`;
      }
    } else {
      let sharedWrapper = el("cmp-wrapper-shared");
      sharedWrapper && (sharedWrapper.style.transform = `translate(${state.panA.x}px, ${state.panA.y}px) scale(${state.zoomA})`);
      let wrapperA = el("cmp-wrapper-a");
      wrapperA && (wrapperA.style.transform = `translate(${state.panA.x}px, ${state.panA.y}px) scale(${state.zoomA})`);
      let wrapperB = el("cmp-wrapper-b");
      if (wrapperB) {
        let activePan = state.syncLock ? state.panA : state.panB, activeZoom = state.syncLock ? state.zoomA : state.zoomB;
        wrapperB.style.transform = `translate(${activePan.x}px, ${activePan.y}px) scale(${activeZoom})`;
      }
      let layerB = el("cmp-layer-b-pinned") || el("cmp-layer-b");
      if (layerB && (state.mode === "h-slider" ? (layerB.style.clipPath = `inset(0 ${clipVal}% 0 0)`, layerB.style.opacity = "1") : state.mode === "v-slider" ? (layerB.style.clipPath = `inset(0 0 ${clipVal}% 0)`, layerB.style.opacity = "1") : state.mode === "onion" ? (layerB.style.clipPath = "none", layerB.style.opacity = (state.onionOpacity / 100).toString()) : (layerB.style.clipPath = "none", layerB.style.opacity = "1")), state.pinSplitterToImage && rect) {
        if (state.mode === "h-slider") {
          let handleH = el("cmp-handle-h");
          if (handleH) {
            let center = rect.width / 2, screenX = (rect.width * (state.splitPos / 100) - center) * state.zoomA + center + state.panA.x;
            handleH.style.left = `calc(${screenX}px - 12px)`;
          }
        } else if (state.mode === "v-slider") {
          let handleV = el("cmp-handle-v");
          if (handleV) {
            let center = rect.height / 2, screenY = (rect.height * (state.splitPos / 100) - center) * state.zoomA + center + state.panA.y;
            handleV.style.top = `calc(${screenY}px - 12px)`;
          }
        }
      } else if (state.mode === "h-slider") {
        let handleH = el("cmp-handle-h");
        handleH && (handleH.style.left = `calc(${state.splitPos}% - 12px)`);
      } else if (state.mode === "v-slider") {
        let handleV = el("cmp-handle-v");
        handleV && (handleV.style.top = `calc(${state.splitPos}% - 12px)`);
      }
    }
    let valEl = el("cmp-zoom-val");
    valEl && (valEl.textContent = Math.round(state.zoomA * 100) + "%");
    let infoA = el("cmp-info-overlay-a");
    infoA && (infoA.textContent = `A: ${state.slotA.width}\xD7${state.slotA.height} | Zoom: ${Math.round(state.zoomA * 100)}%`);
    let infoB = el("cmp-info-overlay-b");
    infoB && (infoB.textContent = `B: ${state.slotB.width}\xD7${state.slotB.height} | Zoom: ${Math.round(
      (state.syncLock ? state.zoomA : state.zoomB) * 100
    )}%`);
  }
  function setupDropZones() {
    setupDropZone(
      TAB_ID,
      ["cmp-drop-zone-a", "cmp-drop-zone-b", "cmp-drop-zone-both"],
      (paths, hitId) => {
        let targetSlot = "A";
        hitId === "cmp-drop-zone-b" && (targetSlot = "B"), paths.length >= 2 ? (loadAssetIntoSlot("A", { path: paths[0], asset_id: 0 }), loadAssetIntoSlot("B", { path: paths[1], asset_id: 0 })) : paths.length === 1 && loadAssetIntoSlot(targetSlot, { path: paths[0], asset_id: 0 });
      }
    );
  }
  function loadFromSelection() {
    PH3.getSelectionAssetContexts().then((selection) => {
      if (!selection || selection.length === 0) {
        alert("No images selected in library grid. Select 1 or 2 images first.");
        return;
      }
      selection.length >= 2 ? (loadAssetIntoSlot("A", selection[0]), loadAssetIntoSlot("B", selection[1])) : loadAssetIntoSlot("A", selection[0]), navigateToTab2();
    });
  }
  function updateSlotHeaders() {
    let titleA = el("slot-a-title"), metaA = el("slot-a-meta");
    titleA && (titleA.textContent = state.slotA.name || "No image loaded", titleA.title = state.slotA.path || state.slotA.name || "No image loaded"), metaA && (metaA.textContent = state.slotA.width ? `${state.slotA.width}\xD7${state.slotA.height}${state.slotA.sizeStr ? ` (${state.slotA.sizeStr})` : ""}` : "");
    let titleB = el("slot-b-title"), metaB = el("slot-b-meta");
    titleB && (titleB.textContent = state.slotB.name || "No image loaded", titleB.title = state.slotB.path || state.slotB.name || "No image loaded"), metaB && (metaB.textContent = state.slotB.width ? `${state.slotB.width}\xD7${state.slotB.height}${state.slotB.sizeStr ? ` (${state.slotB.sizeStr})` : ""}` : "");
  }
  function bindEvents(wrapper) {
    let btnSide = wrapper.querySelector("#cmp-mode-side"), btnHSlider = wrapper.querySelector("#cmp-mode-hslider"), btnVSlider = wrapper.querySelector("#cmp-mode-vslider"), btnOnion = wrapper.querySelector("#cmp-mode-onion");
    function setMode(newMode) {
      state.mode = newMode, [btnSide, btnHSlider, btnVSlider, btnOnion].forEach((b) => {
        b == null || b.classList.remove("primary");
      }), newMode === "side-by-side" && btnSide && btnSide.classList.add("primary"), newMode === "h-slider" && btnHSlider && btnHSlider.classList.add("primary"), newMode === "v-slider" && btnVSlider && btnVSlider.classList.add("primary"), newMode === "onion" && btnOnion && btnOnion.classList.add("primary");
      let secBar = el("cmp-secondary-bar"), sLabel = el("cmp-slider-label"), sRange = el("cmp-slider-range"), sVal = el("cmp-slider-val");
      secBar && (newMode === "side-by-side" ? secBar.style.display = "none" : (secBar.style.display = "flex", newMode === "onion" ? (sLabel && (sLabel.textContent = "Onion Opacity (Image B):"), sRange && (sRange.value = String(state.onionOpacity)), sVal && (sVal.textContent = state.onionOpacity + "%")) : (sLabel && (sLabel.textContent = "Split Position:"), sRange && (sRange.value = String(state.splitPos)), sVal && (sVal.textContent = state.splitPos + "%")))), renderCanvasDOM();
    }
    btnSide && btnSide.addEventListener("click", () => setMode("side-by-side")), btnHSlider && btnHSlider.addEventListener("click", () => setMode("h-slider")), btnVSlider && btnVSlider.addEventListener("click", () => setMode("v-slider")), btnOnion && btnOnion.addEventListener("click", () => setMode("onion"));
    let rangeEl = wrapper.querySelector("#cmp-slider-range");
    rangeEl && rangeEl.addEventListener("input", (e) => {
      let v = parseInt(e.target.value, 10);
      state.mode === "onion" ? state.onionOpacity = v : state.splitPos = v;
      let valEl = el("cmp-slider-val");
      valEl && (valEl.textContent = v + "%"), scheduleTransformUpdate();
    });
    let syncBtn = wrapper.querySelector("#cmp-toggle-sync");
    syncBtn && syncBtn.addEventListener("click", () => {
      state.syncLock = !state.syncLock, state.syncLock ? (syncBtn.classList.add("primary"), syncBtn.innerHTML = '<i class="bi bi-lock-fill"></i> Sync Lock', state.zoomB = state.zoomA, state.panB = { x: state.panA.x, y: state.panA.y }) : (syncBtn.classList.remove("primary"), syncBtn.innerHTML = '<i class="bi bi-unlock"></i> Independent'), scheduleTransformUpdate();
    });
    let pinBtn = wrapper.querySelector("#cmp-toggle-pin-split");
    pinBtn && pinBtn.addEventListener("click", () => {
      state.pinSplitterToImage = !state.pinSplitterToImage, state.pinSplitterToImage ? (pinBtn.classList.add("primary"), pinBtn.innerHTML = '<i class="bi bi-pin-angle-fill"></i> Splitter: Pinned to Image') : (pinBtn.classList.remove("primary"), pinBtn.innerHTML = '<i class="bi bi-window"></i> Splitter: Viewport'), renderCanvasDOM();
    });
    let zoomInBtn = wrapper.querySelector("#cmp-zoom-in"), zoomOutBtn = wrapper.querySelector("#cmp-zoom-out"), zoomFitBtn = wrapper.querySelector("#cmp-zoom-fit"), zoom100Btn = wrapper.querySelector("#cmp-zoom-100"), zoomResetBtn = wrapper.querySelector("#cmp-zoom-reset");
    zoomInBtn && zoomInBtn.addEventListener("click", () => {
      state.zoomA = Math.min(state.zoomA * 1.25, 10), state.syncLock && (state.zoomB = state.zoomA), scheduleTransformUpdate();
    }), zoomOutBtn && zoomOutBtn.addEventListener("click", () => {
      state.zoomA = Math.max(state.zoomA / 1.25, 0.1), state.syncLock && (state.zoomB = state.zoomA), scheduleTransformUpdate();
    }), zoomFitBtn && zoomFitBtn.addEventListener("click", fitToViewport), zoom100Btn && zoom100Btn.addEventListener("click", () => {
      state.zoomA = 1, state.panA = { x: 0, y: 0 }, state.syncLock && (state.zoomB = 1, state.panB = { x: 0, y: 0 }), scheduleTransformUpdate();
    }), zoomResetBtn && zoomResetBtn.addEventListener("click", resetZoomAndPan);
    let loadSelBtn = wrapper.querySelector("#cmp-load-sel-btn");
    loadSelBtn && loadSelBtn.addEventListener("click", loadFromSelection);
    let swapBtn = wrapper.querySelector("#cmp-swap-btn");
    swapBtn && swapBtn.addEventListener("click", swapSlots);
    let infoBtn = wrapper.querySelector("#cmp-toggle-info");
    infoBtn && infoBtn.addEventListener("click", () => {
      state.showInfoOverlay = !state.showInfoOverlay, infoBtn.classList.toggle("primary", state.showInfoOverlay);
      let oA = el("cmp-info-overlay-a"), oB = el("cmp-info-overlay-b");
      oA && (oA.style.display = state.showInfoOverlay ? "block" : "none"), oB && (oB.style.display = state.showInfoOverlay ? "block" : "none");
    });
    let clearBtn = wrapper.querySelector("#cmp-clear-all");
    clearBtn && clearBtn.addEventListener("click", () => {
      state.slotA = { id: null, path: "", url: "", name: "Image A", width: 0, height: 0, sizeStr: "" }, state.slotB = { id: null, path: "", url: "", name: "Image B", width: 0, height: 0, sizeStr: "" }, resetZoomAndPan(), updateSlotHeaders(), renderCanvasDOM();
    });
    let inputA = wrapper.querySelector("#slot-a-file-input");
    inputA && inputA.addEventListener("change", (e) => {
      let files = e.target.files;
      files && files[0] && loadAssetIntoSlot("A", null, files[0]);
    });
    let inputB = wrapper.querySelector("#slot-b-file-input");
    inputB && inputB.addEventListener("change", (e) => {
      let files = e.target.files;
      files && files[0] && loadAssetIntoSlot("B", null, files[0]);
    });
    let clearABtn = wrapper.querySelector("#slot-a-clear-btn");
    clearABtn && clearABtn.addEventListener("click", () => {
      state.slotA = { id: null, path: "", url: "", name: "Image A", width: 0, height: 0, sizeStr: "" }, updateSlotHeaders(), renderCanvasDOM();
    });
    let clearBBtn = wrapper.querySelector("#slot-b-clear-btn");
    clearBBtn && clearBBtn.addEventListener("click", () => {
      state.slotB = { id: null, path: "", url: "", name: "Image B", width: 0, height: 0, sizeStr: "" }, updateSlotHeaders(), renderCanvasDOM();
    });
  }
  function renderCanvasDOM() {
    let canvasArea = el("compare-canvas-area");
    if (!canvasArea) return;
    canvasArea.innerHTML = "", canvasArea.style.background = "var(--sys-window-bg, #ffffff)";
    let overlayA = state.slotA.url ? `<div id="cmp-info-overlay-a" style="position: absolute; bottom: 8px; left: 8px; background: rgba(0,0,0,0.8); color: #ffffff; padding: 4px 8px; border-radius: 2px; font-size: 10px; font-family: monospace; pointer-events: none; z-index: 10; display: ${state.showInfoOverlay ? "block" : "none"}; border: 1px solid #444;">
        A: ${state.slotA.width}\xD7${state.slotA.height} | Zoom: ${Math.round(state.zoomA * 100)}%
      </div>` : "", overlayB = state.slotB.url ? `<div id="cmp-info-overlay-b" style="position: absolute; bottom: 8px; right: 8px; background: rgba(0,0,0,0.8); color: #ffffff; padding: 4px 8px; border-radius: 2px; font-size: 10px; font-family: monospace; pointer-events: none; z-index: 10; display: ${state.showInfoOverlay ? "block" : "none"}; border: 1px solid #444;">
        B: ${state.slotB.width}\xD7${state.slotB.height} | Zoom: ${Math.round(state.zoomB * 100)}%
      </div>` : "";
    state.mode === "side-by-side" ? renderSideBySideDOM(canvasArea, overlayA, overlayB) : state.mode === "h-slider" ? renderHSliderDOM(canvasArea, overlayA, overlayB) : state.mode === "v-slider" ? renderVSliderDOM(canvasArea, overlayA, overlayB) : state.mode === "onion" && renderOnionSkinDOM(canvasArea, overlayA, overlayB), attachCanvasInteractions(canvasArea), scheduleTransformUpdate();
  }
  function placeholderHtml(slotName, targetSlot, zoneId) {
    return `
    <div style="height: 100%; width: 100%; padding: 12px; box-sizing: border-box; display: flex; flex-direction: column; background: var(--sys-window-bg, #ffffff);">
      <div class="toolbox-drop-zone" id="${zoneId}" data-slot="${targetSlot}" style="flex: 1; margin-top: 0; cursor: pointer;">
        <div class="toolbox-drop-icon"><i class="bi bi-images"></i></div>
        <span>Drag & Drop image here to compare</span>
        <span style="font-size: 10px; font-weight: 600; color: var(--sys-border-focus, #0078d7); margin-top: 4px;">Target: ${slotName}</span>
      </div>
    </div>
  `;
  }
  function renderSideBySideDOM(container, overlayA, overlayB) {
    container.style.display = "flex", container.style.height = "100%";
    let vpA = document.createElement("div");
    vpA.className = "cmp-viewport", vpA.dataset.slot = "A", vpA.style.cssText = "flex: 1; position: relative; overflow: hidden; border-right: 1px solid var(--sys-border-dark, #b0b0b0); height: 100%; cursor: " + (state.slotA.url ? "grab" : "default") + "; background: " + (state.slotA.url ? "#1e1e1e" : "var(--sys-window-bg, #ffffff)") + ";", state.slotA.url ? vpA.innerHTML = `
      <div id="cmp-wrapper-a" class="cmp-img-wrapper" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; transform-origin: center center; padding: 12px; box-sizing: border-box; will-change: transform;">
        <img src="${state.slotA.url}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />
      </div>
      ${overlayA}
    ` : vpA.innerHTML = placeholderHtml("Image A", "A", "cmp-drop-zone-a");
    let vpB = document.createElement("div");
    vpB.className = "cmp-viewport", vpB.dataset.slot = "B", vpB.style.cssText = "flex: 1; position: relative; overflow: hidden; height: 100%; cursor: " + (state.slotB.url ? "grab" : "default") + "; background: " + (state.slotB.url ? "#1e1e1e" : "var(--sys-window-bg, #ffffff)") + ";", state.slotB.url ? vpB.innerHTML = `
      <div id="cmp-wrapper-b" class="cmp-img-wrapper" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; transform-origin: center center; padding: 12px; box-sizing: border-box; will-change: transform;">
        <img src="${state.slotB.url}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />
      </div>
      ${overlayB}
    ` : vpB.innerHTML = placeholderHtml("Image B", "B", "cmp-drop-zone-b"), container.appendChild(vpA), container.appendChild(vpB);
  }
  function renderHSliderDOM(container, overlayA, overlayB) {
    if (container.style.display = "block", container.style.height = "100%", !state.slotA.url && !state.slotB.url) {
      container.innerHTML = placeholderHtml("Image A & B", "both", "cmp-drop-zone-both");
      return;
    }
    let clipVal = 100 - state.splitPos;
    state.pinSplitterToImage ? container.innerHTML = `
      <div class="cmp-viewport" data-slot="both" style="position: absolute; inset: 0; overflow: hidden; cursor: grab; background: #1e1e1e;">
        <div id="cmp-wrapper-shared" style="position: absolute; inset: 0; transform-origin: center center; will-change: transform;">
          <div style="position: absolute; inset: 0; padding: 12px; box-sizing: border-box; display: flex; align-items: center; justify-content: center;">
            <img src="${state.slotA.url || ""}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none; display: ${state.slotA.url ? "block" : "none"};" />
          </div>
          <div id="cmp-layer-b-pinned" style="position: absolute; inset: 0; overflow: hidden; clip-path: inset(0 ${clipVal}% 0 0); will-change: clip-path; display: ${state.slotB.url ? "block" : "none"};">
            <div style="position: absolute; inset: 0; padding: 12px; box-sizing: border-box; display: flex; align-items: center; justify-content: center;">
              <img src="${state.slotB.url || ""}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />
            </div>
          </div>
        </div>
        <div id="cmp-handle-h" style="position: absolute; top: 0; bottom: 0; left: calc(50% - 12px); width: 24px; cursor: col-resize; display: flex; align-items: center; justify-content: center; z-index: 20; will-change: left;">
          <div style="position: absolute; top: 0; bottom: 0; left: 11px; width: 2px; background: #0078d7;"></div>
          <div class="win-button primary" style="width: 24px; height: 32px; padding: 0; border-radius: 2px; display: flex; align-items: center; justify-content: center; font-size: 12px; z-index: 1;">
            <i class="bi bi-arrows-collapse"></i>
          </div>
        </div>
        ${overlayA}
        ${overlayB}
      </div>
    ` : container.innerHTML = `
      <div class="cmp-viewport" data-slot="both" style="position: absolute; inset: 0; overflow: hidden; cursor: grab; background: #1e1e1e;">
        <div class="cmp-layer-a" style="position: absolute; inset: 0; overflow: hidden;">
          <div id="cmp-wrapper-a" class="cmp-img-wrapper" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; transform-origin: center center; padding: 12px; box-sizing: border-box; will-change: transform;">
            ${state.slotA.url ? `<img src="${state.slotA.url}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />` : ""}
          </div>
        </div>
        <div id="cmp-layer-b" class="cmp-layer-b" style="position: absolute; inset: 0; overflow: hidden; clip-path: inset(0 ${clipVal}% 0 0); will-change: clip-path;">
          <div id="cmp-wrapper-b" class="cmp-img-wrapper" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; transform-origin: center center; padding: 12px; box-sizing: border-box; will-change: transform;">
            ${state.slotB.url ? `<img src="${state.slotB.url}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />` : ""}
          </div>
        </div>
        <div id="cmp-handle-h" style="position: absolute; top: 0; bottom: 0; left: calc(${state.splitPos}% - 12px); width: 24px; cursor: col-resize; display: flex; align-items: center; justify-content: center; z-index: 20; will-change: left;">
          <div style="position: absolute; top: 0; bottom: 0; left: 11px; width: 2px; background: #0078d7;"></div>
          <div class="win-button primary" style="width: 24px; height: 32px; padding: 0; border-radius: 2px; display: flex; align-items: center; justify-content: center; font-size: 12px; z-index: 1;">
            <i class="bi bi-arrows-collapse"></i>
          </div>
        </div>
        ${overlayA}
        ${overlayB}
      </div>
    `;
  }
  function renderVSliderDOM(container, overlayA, overlayB) {
    if (container.style.display = "block", container.style.height = "100%", !state.slotA.url && !state.slotB.url) {
      container.innerHTML = placeholderHtml("Image A & B", "both", "cmp-drop-zone-both");
      return;
    }
    let clipVal = 100 - state.splitPos;
    state.pinSplitterToImage ? container.innerHTML = `
      <div class="cmp-viewport" data-slot="both" style="position: absolute; inset: 0; overflow: hidden; cursor: grab; background: #1e1e1e;">
        <div id="cmp-wrapper-shared" style="position: absolute; inset: 0; transform-origin: center center; will-change: transform;">
          <div style="position: absolute; inset: 0; padding: 12px; box-sizing: border-box; display: flex; align-items: center; justify-content: center;">
            <img src="${state.slotA.url || ""}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none; display: ${state.slotA.url ? "block" : "none"};" />
          </div>
          <div id="cmp-layer-b-pinned" style="position: absolute; inset: 0; overflow: hidden; clip-path: inset(0 0 ${clipVal}% 0); will-change: clip-path; display: ${state.slotB.url ? "block" : "none"};">
            <div style="position: absolute; inset: 0; padding: 12px; box-sizing: border-box; display: flex; align-items: center; justify-content: center;">
              <img src="${state.slotB.url || ""}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />
            </div>
          </div>
        </div>
        <div id="cmp-handle-v" style="position: absolute; left: 0; right: 0; top: calc(50% - 12px); height: 24px; cursor: row-resize; display: flex; align-items: center; justify-content: center; z-index: 20; will-change: top;">
          <div style="position: absolute; left: 0; right: 0; top: 11px; height: 2px; background: #0078d7;"></div>
          <div class="win-button primary" style="width: 32px; height: 24px; padding: 0; border-radius: 2px; display: flex; align-items: center; justify-content: center; font-size: 12px; z-index: 1;">
            <i class="bi bi-arrows-collapse-vertical"></i>
          </div>
        </div>
        ${overlayA}
        ${overlayB}
      </div>
    ` : container.innerHTML = `
      <div class="cmp-viewport" data-slot="both" style="position: absolute; inset: 0; overflow: hidden; cursor: grab; background: #1e1e1e;">
        <div class="cmp-layer-a" style="position: absolute; inset: 0; overflow: hidden;">
          <div id="cmp-wrapper-a" class="cmp-img-wrapper" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; transform-origin: center center; padding: 12px; box-sizing: border-box; will-change: transform;">
            ${state.slotA.url ? `<img src="${state.slotA.url}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />` : ""}
          </div>
        </div>
        <div id="cmp-layer-b" class="cmp-layer-b" style="position: absolute; inset: 0; overflow: hidden; clip-path: inset(0 0 ${clipVal}% 0); will-change: clip-path;">
          <div id="cmp-wrapper-b" class="cmp-img-wrapper" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; transform-origin: center center; padding: 12px; box-sizing: border-box; will-change: transform;">
            ${state.slotB.url ? `<img src="${state.slotB.url}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />` : ""}
          </div>
        </div>
        <div id="cmp-handle-v" style="position: absolute; left: 0; right: 0; top: calc(${state.splitPos}% - 12px); height: 24px; cursor: row-resize; display: flex; align-items: center; justify-content: center; z-index: 20; will-change: top;">
          <div style="position: absolute; left: 0; right: 0; top: 11px; height: 2px; background: #0078d7;"></div>
          <div class="win-button primary" style="width: 32px; height: 24px; padding: 0; border-radius: 2px; display: flex; align-items: center; justify-content: center; font-size: 12px; z-index: 1;">
            <i class="bi bi-arrows-collapse-vertical"></i>
          </div>
        </div>
        ${overlayA}
        ${overlayB}
      </div>
    `;
  }
  function renderOnionSkinDOM(container, overlayA, overlayB) {
    if (container.style.display = "block", container.style.height = "100%", !state.slotA.url && !state.slotB.url) {
      container.innerHTML = placeholderHtml("Image A & B", "both", "cmp-drop-zone-both");
      return;
    }
    let opacityVal = state.onionOpacity / 100;
    container.innerHTML = `
    <div class="cmp-viewport" data-slot="both" style="position: absolute; inset: 0; overflow: hidden; cursor: grab; background: #1e1e1e;">
      <div class="cmp-layer-a" style="position: absolute; inset: 0; overflow: hidden;">
        <div id="cmp-wrapper-a" class="cmp-img-wrapper" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; transform-origin: center center; padding: 12px; box-sizing: border-box; will-change: transform;">
          ${state.slotA.url ? `<img src="${state.slotA.url}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />` : ""}
        </div>
      </div>
      <div id="cmp-layer-b" class="cmp-layer-b" style="position: absolute; inset: 0; overflow: hidden; opacity: ${opacityVal}; will-change: opacity;">
        <div id="cmp-wrapper-b" class="cmp-img-wrapper" style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; transform-origin: center center; padding: 12px; box-sizing: border-box; will-change: transform;">
          ${state.slotB.url ? `<img src="${state.slotB.url}" style="max-width: 100%; max-height: 100%; width: auto; height: auto; object-fit: contain; pointer-events: none;" />` : ""}
        </div>
      </div>
      ${overlayA}
      ${overlayB}
    </div>
  `;
  }
  function processDroppedItems(dataTransfer, targetSlot) {
    if (!dataTransfer) return;
    if (dataTransfer.files && dataTransfer.files.length > 0) {
      let fileList = Array.from(dataTransfer.files);
      fileList.length >= 2 ? (loadAssetIntoSlot("A", null, fileList[0]), loadAssetIntoSlot("B", null, fileList[1])) : loadAssetIntoSlot(targetSlot, null, fileList[0]);
      return;
    }
    if (dataTransfer.items && dataTransfer.items.length > 0) {
      let fileItems = Array.from(dataTransfer.items).filter((it) => it.kind === "file");
      if (fileItems.length > 0) {
        let files = fileItems.map((it) => it.getAsFile()).filter(Boolean);
        files.length >= 2 ? (loadAssetIntoSlot("A", null, files[0]), loadAssetIntoSlot("B", null, files[1])) : files.length === 1 && loadAssetIntoSlot(targetSlot, null, files[0]);
        return;
      }
    }
    let uriList = dataTransfer.getData("text/uri-list"), plainText = dataTransfer.getData("text/plain"), rawPath = uriList || plainText;
    if (rawPath) {
      let lines = rawPath.split(/\r?\n/).map((s) => s.trim()).filter(Boolean);
      lines.length >= 2 ? (loadAssetIntoSlot("A", { path: lines[0], asset_id: 0 }), loadAssetIntoSlot("B", { path: lines[1], asset_id: 0 })) : lines.length === 1 && loadAssetIntoSlot(targetSlot, { path: lines[0], asset_id: 0 });
    }
  }
  function attachCanvasInteractions(container) {
    container.querySelectorAll(".cmp-viewport").forEach((vp) => {
      let slotType = vp.dataset.slot || "both";
      vp.addEventListener("click", (e) => {
        let dz = e.target.closest(".toolbox-drop-zone");
        if (dz) {
          let targetSlot = dz.dataset.slot === "B" ? "B" : "A", input = el(targetSlot === "B" ? "slot-b-file-input" : "slot-a-file-input");
          input && input.click();
        }
      }), vp.addEventListener(
        "wheel",
        (e) => {
          e.preventDefault();
          let delta = e.deltaY < 0 ? 1.15 : 0.85;
          (state.syncLock || slotType === "both" || slotType === "A") && (state.zoomA = Math.min(Math.max(state.zoomA * delta, 0.1), 10)), (state.syncLock || slotType === "both" || slotType === "B") && (state.zoomB = state.syncLock ? state.zoomA : Math.min(Math.max(state.zoomB * delta, 0.1), 10)), scheduleTransformUpdate();
        },
        { passive: !1 }
      ), vp.addEventListener("mousedown", (e) => {
        let handleH = el("cmp-handle-h"), handleV = el("cmp-handle-v");
        if (handleH && handleH.contains(e.target) || handleV && handleV.contains(e.target)) {
          state.isDraggingSlider = !0;
          return;
        }
        e.button === 0 && (state.isDraggingPan = !0, state.dragTargetSlot = slotType, state.panStartX = e.clientX, state.panStartY = e.clientY, state.panInitialA = { x: state.panA.x, y: state.panA.y }, state.panInitialB = { x: state.panB.x, y: state.panB.y }, vp.style.cursor = "grabbing");
      }), vp.addEventListener("dragenter", (e) => {
        e.preventDefault(), e.stopPropagation(), e.dataTransfer && (e.dataTransfer.dropEffect = "copy");
        let dz = vp.querySelector(".toolbox-drop-zone");
        dz == null || dz.classList.add("toolbox-drop-active");
      }), vp.addEventListener("dragover", (e) => {
        e.preventDefault(), e.stopPropagation(), e.dataTransfer && (e.dataTransfer.dropEffect = "copy");
        let dz = vp.querySelector(".toolbox-drop-zone");
        dz == null || dz.classList.add("toolbox-drop-active");
      }), vp.addEventListener("dragleave", (e) => {
        e.preventDefault(), e.stopPropagation();
        let dz = vp.querySelector(".toolbox-drop-zone");
        dz == null || dz.classList.remove("toolbox-drop-active");
      }), vp.addEventListener("drop", (e) => {
        e.preventDefault(), e.stopPropagation();
        let dz = vp.querySelector(".toolbox-drop-zone");
        dz == null || dz.classList.remove("toolbox-drop-active");
        let targetSlot = slotType === "B" ? "B" : "A";
        processDroppedItems(e.dataTransfer, targetSlot);
      });
    });
  }
  function bindGlobalEventsOnce() {
    state.globalEventsBound || (state.globalEventsBound = !0, window.addEventListener("mousemove", (e) => {
      let container = el("compare-canvas-area");
      if (container) {
        if (state.isDraggingSlider) {
          let rect = container.getBoundingClientRect();
          if (state.mode === "h-slider") {
            let pct = 50;
            if (state.pinSplitterToImage) {
              let center = rect.width / 2;
              pct = ((e.clientX - rect.left - center - state.panA.x) / state.zoomA + center) / rect.width * 100;
            } else
              pct = (e.clientX - rect.left) / rect.width * 100;
            state.splitPos = Math.min(Math.max(Math.round(pct), 0), 100);
            let sRange = el("cmp-slider-range"), sVal = el("cmp-slider-val");
            sRange && (sRange.value = String(state.splitPos)), sVal && (sVal.textContent = state.splitPos + "%"), scheduleTransformUpdate();
          } else if (state.mode === "v-slider") {
            let pct = 50;
            if (state.pinSplitterToImage) {
              let center = rect.height / 2;
              pct = ((e.clientY - rect.top - center - state.panA.y) / state.zoomA + center) / rect.height * 100;
            } else
              pct = (e.clientY - rect.top) / rect.height * 100;
            state.splitPos = Math.min(Math.max(Math.round(pct), 0), 100);
            let sRange = el("cmp-slider-range"), sVal = el("cmp-slider-val");
            sRange && (sRange.value = String(state.splitPos)), sVal && (sVal.textContent = state.splitPos + "%"), scheduleTransformUpdate();
          }
          return;
        }
        if (state.isDraggingPan) {
          let dx = e.clientX - state.panStartX, dy = e.clientY - state.panStartY;
          (state.syncLock || state.dragTargetSlot === "both" || state.dragTargetSlot === "A") && (state.panA.x = state.panInitialA.x + dx, state.panA.y = state.panInitialA.y + dy), (state.syncLock || state.dragTargetSlot === "both" || state.dragTargetSlot === "B") && (state.panB.x = state.syncLock ? state.panA.x : state.panInitialB.x + dx, state.panB.y = state.syncLock ? state.panA.y : state.panInitialB.y + dy), scheduleTransformUpdate();
        }
      }
    }), window.addEventListener("mouseup", () => {
      (state.isDraggingPan || state.isDraggingSlider) && (state.isDraggingPan = !1, state.isDraggingSlider = !1, document.querySelectorAll(".cmp-viewport").forEach((vp) => {
        vp.style.cursor = "grab";
      }));
    }));
  }
  function renderCompareTab() {
    let wrapper = document.createElement("div");
    return wrapper.style.cssText = "display: flex; flex-direction: column; height: calc(100vh - 130px); min-height: 500px; gap: 10px; box-sizing: border-box; overflow: hidden;", wrapper.innerHTML = `
    <!-- Control Bar Container -->
    <div class="group-box" style="margin-bottom: 0; padding: 8px 12px;">
      <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 8px;">
        <!-- Left: Mode Selection Controls -->
        <div style="display: flex; align-items: center; gap: 4px;">
          <span style="font-weight: 600; font-size: 11px; margin-right: 6px; color: var(--sys-text-subtle, #555);">Mode:</span>
          <button type="button" class="win-button ${state.mode === "side-by-side" ? "primary" : ""}" id="cmp-mode-side" title="Side-by-Side Dual Viewports">
            <i class="bi bi-layout-split"></i> Side-by-Side
          </button>
          <button type="button" class="win-button ${state.mode === "h-slider" ? "primary" : ""}" id="cmp-mode-hslider" title="Horizontal Split Slider">
            <i class="bi bi-sliders"></i> H-Slider
          </button>
          <button type="button" class="win-button ${state.mode === "v-slider" ? "primary" : ""}" id="cmp-mode-vslider" title="Vertical Split Slider">
            <i class="bi bi-sliders2-vertical"></i> V-Slider
          </button>
          <button type="button" class="win-button ${state.mode === "onion" ? "primary" : ""}" id="cmp-mode-onion" title="Onion Skin Opacity Overlay">
            <i class="bi bi-layers-half"></i> Onion Skin
          </button>
        </div>

        <!-- Middle: Sync, Pin, & Zoom Controls -->
        <div style="display: flex; align-items: center; gap: 6px;">
          <button type="button" class="win-button ${state.syncLock ? "primary" : ""}" id="cmp-toggle-sync" title="Toggle Synchronized Zoom & Pan">
            <i class="bi ${state.syncLock ? "bi-lock-fill" : "bi-unlock"}"></i> ${state.syncLock ? "Sync Lock" : "Independent"}
          </button>
          <button type="button" class="win-button ${state.pinSplitterToImage ? "primary" : ""}" id="cmp-toggle-pin-split" title="Toggle Splitter Mode: Viewport Screen Wipe vs Pinned to Image Pixel Space">
            <i class="bi ${state.pinSplitterToImage ? "bi-pin-angle-fill" : "bi-window"}"></i> ${state.pinSplitterToImage ? "Splitter: Pinned to Image" : "Splitter: Viewport"}
          </button>

          <div style="height: 16px; width: 1px; background: var(--sys-border-dark, #b0b0b0); margin: 0 4px;"></div>
          <button type="button" class="win-button" id="cmp-zoom-out" title="Zoom Out"><i class="bi bi-zoom-out"></i></button>
          <span id="cmp-zoom-val" style="font-size: 11px; font-family: monospace; min-width: 45px; text-align: center;">100%</span>
          <button type="button" class="win-button" id="cmp-zoom-in" title="Zoom In"><i class="bi bi-zoom-in"></i></button>
          <button type="button" class="win-button" id="cmp-zoom-fit" title="Fit to Viewport">Fit</button>
          <button type="button" class="win-button" id="cmp-zoom-100" title="100% Zoom">100%</button>
          <button type="button" class="win-button" id="cmp-zoom-reset" title="Reset View"><i class="bi bi-arrow-counterclockwise"></i> Reset</button>
        </div>

        <!-- Right: Actions & Selection -->
        <div style="display: flex; align-items: center; gap: 6px;">
          <button type="button" class="win-button" id="cmp-load-sel-btn" title="Load selected images from active selection (up to 2)">
            <i class="bi bi-check2-square"></i> Compare Selected
          </button>
          <button type="button" class="win-button" id="cmp-swap-btn" title="Swap Image A and Image B">
            <i class="bi bi-arrow-left-right"></i> Swap A/B
          </button>
          <button type="button" class="win-button ${state.showInfoOverlay ? "primary" : ""}" id="cmp-toggle-info" title="Toggle Metadata Overlay">
            <i class="bi bi-info-circle"></i> Info Overlay
          </button>
          <button type="button" class="win-button danger" id="cmp-clear-all" title="Clear Loaded Images">
            <i class="bi bi-trash"></i> Clear
          </button>
        </div>
      </div>

      <!-- Secondary Controls Bar (for Slider & Onion modes) -->
      <div id="cmp-secondary-bar" style="display: none; align-items: center; gap: 12px; margin-top: 8px; padding-top: 6px; border-top: 1px dashed var(--sys-border-dark, #b0b0b0);">
        <div id="cmp-slider-ctrl" style="display: flex; align-items: center; gap: 8px; flex: 1;">
          <span style="font-size: 11px; font-weight: 500;" id="cmp-slider-label">Split Position:</span>
          <input type="range" id="cmp-slider-range" min="0" max="100" value="50" style="flex: 1; height: 4px; cursor: pointer;" />
          <span id="cmp-slider-val" style="font-size: 11px; font-family: monospace; width: 35px;">50%</span>
        </div>
      </div>
    </div>

    <!-- Slots Header Bar -->
    <div style="display: flex; gap: 10px; flex-shrink: 0;">
      <!-- Slot A Header Group Box -->
      <div class="group-box" style="flex: 1; margin-bottom: 0; padding: 6px 10px;" id="slot-a-header">
        <div style="display: flex; align-items: center; justify-content: space-between;">
          <div style="display: flex; align-items: center; gap: 6px; min-width: 0; flex: 1;">
            <span class="tag-pill custom-concept" style="font-size: 10px; font-weight: 600;"><i class="bi bi-stars"></i> Image A</span>
            <span id="slot-a-title" style="font-size: 11px; font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; color: var(--sys-control-text, #000);" title="No image loaded">
              No image loaded
            </span>
            <span id="slot-a-meta" style="font-size: 10px; color: var(--sys-text-subtle, #555); font-family: monospace;"></span>
          </div>
          <div style="display: flex; align-items: center; gap: 4px; margin-left: 8px;">
            <label class="win-button" style="font-size: 10px; padding: 1px 6px; cursor: pointer; margin: 0;">
              <i class="bi bi-folder2-open"></i> Browse
              <input type="file" id="slot-a-file-input" accept="image/*" style="display: none;" />
            </label>
            <button type="button" class="win-button" id="slot-a-clear-btn" style="font-size: 10px; padding: 1px 6px;" title="Clear Image A">
              <i class="bi bi-x-lg"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Slot B Header Group Box -->
      <div class="group-box" style="flex: 1; margin-bottom: 0; padding: 6px 10px;" id="slot-b-header">
        <div style="display: flex; align-items: center; justify-content: space-between;">
          <div style="display: flex; align-items: center; justify-content: space-between; width: 100%;">
            <div style="display: flex; align-items: center; gap: 6px; min-width: 0; flex: 1;">
              <span class="tag-pill tag-character" style="font-size: 10px; font-weight: 600;">Image B</span>
              <span id="slot-b-title" style="font-size: 11px; font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; color: var(--sys-control-text, #000);" title="No image loaded">
                No image loaded
              </span>
              <span id="slot-b-meta" style="font-size: 10px; color: var(--sys-text-subtle, #555); font-family: monospace;"></span>
            </div>
            <div style="display: flex; align-items: center; gap: 4px; margin-left: 8px;">
              <label class="win-button" style="font-size: 10px; padding: 1px 6px; cursor: pointer; margin: 0;">
                <i class="bi bi-folder2-open"></i> Browse
                <input type="file" id="slot-b-file-input" accept="image/*" style="display: none;" />
              </label>
              <button type="button" class="win-button" id="slot-b-clear-btn" style="font-size: 10px; padding: 1px 6px;" title="Clear Image B">
                <i class="bi bi-x-lg"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Main Canvas Container -->
    <div id="compare-canvas-area" style="flex: 1; min-height: 400px; position: relative; background: var(--sys-window-bg, #ffffff); border: 1px solid var(--sys-border-dark, #b0b0b0); border-radius: 2px; overflow: hidden; user-select: none;">
      <!-- Canvas Content rendered dynamically -->
    </div>
  `, setTimeout(() => {
      bindEvents(wrapper), bindGlobalEventsOnce(), setupDropZones(), updateSlotHeaders(), renderCanvasDOM();
    }, 0), wrapper;
  }

  // image-compare/src/index.ts
  var PH4 = window.PluginHost;
  PH4 ? (PH4.registerTab(TAB_ID, "Image Compare", "bi bi-layout-split", renderCompareTab), PH4.registerMetadataRenderer("image-compare-modal-section", (asset) => {
    if (!asset || !asset.path) return null;
    let box = document.createElement("div");
    box.className = "group-box", box.style.cssText = "margin-top:8px;", box.innerHTML = '<div class="group-box-title"><i class="bi bi-layout-split"></i> Image Compare</div><div style="display:flex;align-items:center;gap:8px;padding:4px 0;">  <span style="font-size:11px;color:#555;flex:1;">Send image to Image Compare tool.</span>  <button type="button" class="win-button" id="cmp-send-slot-a">    <i class="bi bi-arrow-left-square"></i> Set as Image A  </button>  <button type="button" class="win-button" id="cmp-send-slot-b">    <i class="bi bi-arrow-right-square"></i> Set as Image B  </button></div>';
    let btnA = box.querySelector("#cmp-send-slot-a");
    btnA == null || btnA.addEventListener("click", () => {
      loadAssetIntoSlot("A", asset), closeInfoModal(), navigateToTab2();
    });
    let btnB = box.querySelector("#cmp-send-slot-b");
    return btnB == null || btnB.addEventListener("click", () => {
      loadAssetIntoSlot("B", asset), closeInfoModal(), navigateToTab2();
    }), box;
  }), PH4.registerToolbarButton("compare-selected", "Compare Selected", "bi bi-layout-split", (selection) => {
    if (!selection || selection.length === 0) {
      alert("No images selected.");
      return;
    }
    selection.length >= 2 ? (loadAssetIntoSlot("A", selection[0]), loadAssetIntoSlot("B", selection[1])) : loadAssetIntoSlot("A", selection[0]), closeInfoModal(), navigateToTab2();
  }), PH4.registerContextMenuItem("send-to-compare-a", "Compare: Set as Image A", (asset) => {
    asset && (loadAssetIntoSlot("A", asset), closeInfoModal(), navigateToTab2());
  }), PH4.registerContextMenuItem("send-to-compare-b", "Compare: Set as Image B", (asset) => {
    asset && (loadAssetIntoSlot("B", asset), closeInfoModal(), navigateToTab2());
  }), console.log("Image Compare plugin initialized successfully.")) : console.error("image-compare: PluginHost not available; aborting.");
})();
